// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#include "dft.h"
#include "AESL_pkg.h"

using namespace std;

namespace ap_rtl {

const sc_logic dft::ap_const_logic_1 = sc_dt::Log_1;
const sc_logic dft::ap_const_logic_0 = sc_dt::Log_0;
const sc_lv<22> dft::ap_ST_fsm_state1 = "1";
const sc_lv<22> dft::ap_ST_fsm_state2 = "10";
const sc_lv<22> dft::ap_ST_fsm_state3 = "100";
const sc_lv<22> dft::ap_ST_fsm_state4 = "1000";
const sc_lv<22> dft::ap_ST_fsm_state5 = "10000";
const sc_lv<22> dft::ap_ST_fsm_state6 = "100000";
const sc_lv<22> dft::ap_ST_fsm_state7 = "1000000";
const sc_lv<22> dft::ap_ST_fsm_state8 = "10000000";
const sc_lv<22> dft::ap_ST_fsm_state9 = "100000000";
const sc_lv<22> dft::ap_ST_fsm_state10 = "1000000000";
const sc_lv<22> dft::ap_ST_fsm_state11 = "10000000000";
const sc_lv<22> dft::ap_ST_fsm_state12 = "100000000000";
const sc_lv<22> dft::ap_ST_fsm_state13 = "1000000000000";
const sc_lv<22> dft::ap_ST_fsm_state14 = "10000000000000";
const sc_lv<22> dft::ap_ST_fsm_pp0_stage0 = "100000000000000";
const sc_lv<22> dft::ap_ST_fsm_pp0_stage1 = "1000000000000000";
const sc_lv<22> dft::ap_ST_fsm_pp0_stage2 = "10000000000000000";
const sc_lv<22> dft::ap_ST_fsm_pp0_stage3 = "100000000000000000";
const sc_lv<22> dft::ap_ST_fsm_pp0_stage4 = "1000000000000000000";
const sc_lv<22> dft::ap_ST_fsm_state57 = "10000000000000000000";
const sc_lv<22> dft::ap_ST_fsm_state58 = "100000000000000000000";
const sc_lv<22> dft::ap_ST_fsm_state59 = "1000000000000000000000";
const sc_lv<32> dft::ap_const_lv32_0 = "00000000000000000000000000000000";
const bool dft::ap_const_boolean_1 = true;
const sc_lv<32> dft::ap_const_lv32_E = "1110";
const bool dft::ap_const_boolean_0 = false;
const sc_lv<32> dft::ap_const_lv32_1 = "1";
const sc_lv<1> dft::ap_const_lv1_0 = "0";
const sc_lv<32> dft::ap_const_lv32_5 = "101";
const sc_lv<32> dft::ap_const_lv32_B = "1011";
const sc_lv<32> dft::ap_const_lv32_D = "1101";
const sc_lv<32> dft::ap_const_lv32_11 = "10001";
const sc_lv<32> dft::ap_const_lv32_10 = "10000";
const sc_lv<32> dft::ap_const_lv32_12 = "10010";
const sc_lv<32> dft::ap_const_lv32_F = "1111";
const sc_lv<32> dft::ap_const_lv32_14 = "10100";
const sc_lv<1> dft::ap_const_lv1_1 = "1";
const sc_lv<9> dft::ap_const_lv9_0 = "000000000";
const sc_lv<32> dft::ap_const_lv32_13 = "10011";
const sc_lv<32> dft::ap_const_lv32_15 = "10101";
const sc_lv<32> dft::ap_const_lv32_C = "1100";
const sc_lv<64> dft::ap_const_lv64_3F9921FB5444261E = "11111110011001001000011111101101010100010001000010011000011110";
const sc_lv<32> dft::ap_const_lv32_6 = "110";
const sc_lv<9> dft::ap_const_lv9_100 = "100000000";
const sc_lv<9> dft::ap_const_lv9_1 = "1";
const sc_lv<64> dft::ap_const_lv64_8000000000000000 = "1000000000000000000000000000000000000000000000000000000000000000";
const sc_lv<2> dft::ap_const_lv2_0 = "00";
const sc_lv<2> dft::ap_const_lv2_1 = "1";

dft::dft(sc_module_name name) : sc_module(name), mVcdFile(0) {
    temp_real_U = new dft_temp_real("temp_real_U");
    temp_real_U->clk(ap_clk);
    temp_real_U->reset(ap_rst);
    temp_real_U->address0(temp_real_address0);
    temp_real_U->ce0(temp_real_ce0);
    temp_real_U->we0(temp_real_we0);
    temp_real_U->d0(temp_real_d0);
    temp_real_U->q0(temp_real_q0);
    temp_imag_U = new dft_temp_real("temp_imag_U");
    temp_imag_U->clk(ap_clk);
    temp_imag_U->reset(ap_rst);
    temp_imag_U->address0(temp_imag_address0);
    temp_imag_U->ce0(temp_imag_ce0);
    temp_imag_U->we0(temp_imag_we0);
    temp_imag_U->d0(temp_imag_d0);
    temp_imag_U->q0(temp_imag_q0);
    grp_sin_or_cos_double_s_fu_219 = new sin_or_cos_double_s("grp_sin_or_cos_double_s_fu_219");
    grp_sin_or_cos_double_s_fu_219->ap_clk(ap_clk);
    grp_sin_or_cos_double_s_fu_219->ap_rst(ap_rst);
    grp_sin_or_cos_double_s_fu_219->ap_start(grp_sin_or_cos_double_s_fu_219_ap_start);
    grp_sin_or_cos_double_s_fu_219->ap_done(grp_sin_or_cos_double_s_fu_219_ap_done);
    grp_sin_or_cos_double_s_fu_219->ap_idle(grp_sin_or_cos_double_s_fu_219_ap_idle);
    grp_sin_or_cos_double_s_fu_219->ap_ready(grp_sin_or_cos_double_s_fu_219_ap_ready);
    grp_sin_or_cos_double_s_fu_219->ap_ce(ap_var_for_const0);
    grp_sin_or_cos_double_s_fu_219->t_in(grp_sin_or_cos_double_s_fu_219_t_in);
    grp_sin_or_cos_double_s_fu_219->do_cos(grp_sin_or_cos_double_s_fu_219_do_cos);
    grp_sin_or_cos_double_s_fu_219->ap_return(grp_sin_or_cos_double_s_fu_219_ap_return);
    dft_faddfsub_32nsibs_U17 = new dft_faddfsub_32nsibs<1,5,32,32,32>("dft_faddfsub_32nsibs_U17");
    dft_faddfsub_32nsibs_U17->clk(ap_clk);
    dft_faddfsub_32nsibs_U17->reset(ap_rst);
    dft_faddfsub_32nsibs_U17->din0(grp_fu_239_p0);
    dft_faddfsub_32nsibs_U17->din1(grp_fu_239_p1);
    dft_faddfsub_32nsibs_U17->opcode(grp_fu_239_opcode);
    dft_faddfsub_32nsibs_U17->ce(ap_var_for_const0);
    dft_faddfsub_32nsibs_U17->dout(grp_fu_239_p2);
    dft_fmul_32ns_32njbC_U18 = new dft_fmul_32ns_32njbC<1,4,32,32,32>("dft_fmul_32ns_32njbC_U18");
    dft_fmul_32ns_32njbC_U18->clk(ap_clk);
    dft_fmul_32ns_32njbC_U18->reset(ap_rst);
    dft_fmul_32ns_32njbC_U18->din0(grp_fu_245_p0);
    dft_fmul_32ns_32njbC_U18->din1(grp_fu_245_p1);
    dft_fmul_32ns_32njbC_U18->ce(ap_var_for_const0);
    dft_fmul_32ns_32njbC_U18->dout(grp_fu_245_p2);
    dft_sitofp_32ns_3kbM_U19 = new dft_sitofp_32ns_3kbM<1,4,32,32>("dft_sitofp_32ns_3kbM_U19");
    dft_sitofp_32ns_3kbM_U19->clk(ap_clk);
    dft_sitofp_32ns_3kbM_U19->reset(ap_rst);
    dft_sitofp_32ns_3kbM_U19->din0(grp_fu_249_p0);
    dft_sitofp_32ns_3kbM_U19->ce(ap_var_for_const0);
    dft_sitofp_32ns_3kbM_U19->dout(grp_fu_249_p1);
    dft_fptrunc_64ns_lbW_U20 = new dft_fptrunc_64ns_lbW<1,2,64,32>("dft_fptrunc_64ns_lbW_U20");
    dft_fptrunc_64ns_lbW_U20->clk(ap_clk);
    dft_fptrunc_64ns_lbW_U20->reset(ap_rst);
    dft_fptrunc_64ns_lbW_U20->din0(grp_fu_252_p0);
    dft_fptrunc_64ns_lbW_U20->ce(ap_var_for_const0);
    dft_fptrunc_64ns_lbW_U20->dout(grp_fu_252_p1);
    dft_fpext_32ns_64mb6_U21 = new dft_fpext_32ns_64mb6<1,2,32,64>("dft_fpext_32ns_64mb6_U21");
    dft_fpext_32ns_64mb6_U21->clk(ap_clk);
    dft_fpext_32ns_64mb6_U21->reset(ap_rst);
    dft_fpext_32ns_64mb6_U21->din0(tmp_4_reg_402);
    dft_fpext_32ns_64mb6_U21->ce(ap_var_for_const0);
    dft_fpext_32ns_64mb6_U21->dout(grp_fu_255_p1);
    dft_dmul_64ns_64nncg_U22 = new dft_dmul_64ns_64nncg<1,6,64,64,64>("dft_dmul_64ns_64nncg_U22");
    dft_dmul_64ns_64nncg_U22->clk(ap_clk);
    dft_dmul_64ns_64nncg_U22->reset(ap_rst);
    dft_dmul_64ns_64nncg_U22->din0(tmp_reg_358);
    dft_dmul_64ns_64nncg_U22->din1(ap_var_for_const1);
    dft_dmul_64ns_64nncg_U22->ce(ap_var_for_const0);
    dft_dmul_64ns_64nncg_U22->dout(grp_fu_259_p2);
    dft_sitodp_32ns_6ocq_U23 = new dft_sitodp_32ns_6ocq<1,5,32,64>("dft_sitodp_32ns_6ocq_U23");
    dft_sitodp_32ns_6ocq_U23->clk(ap_clk);
    dft_sitodp_32ns_6ocq_U23->reset(ap_rst);
    dft_sitodp_32ns_6ocq_U23->din0(grp_fu_264_p0);
    dft_sitodp_32ns_6ocq_U23->ce(ap_var_for_const0);
    dft_sitodp_32ns_6ocq_U23->dout(grp_fu_264_p1);

    SC_METHOD(thread_ap_clk_no_reset_);
    dont_initialize();
    sensitive << ( ap_clk.pos() );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage0);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage3);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_pp0_stage4);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state1);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state12);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state13);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state14);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state2);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state57);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state58);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state59);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state6);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_CS_fsm_state7);
    sensitive << ( ap_CS_fsm );

    SC_METHOD(thread_ap_block_pp0_stage0);

    SC_METHOD(thread_ap_block_pp0_stage0_00001);

    SC_METHOD(thread_ap_block_pp0_stage0_11001);

    SC_METHOD(thread_ap_block_pp0_stage0_subdone);

    SC_METHOD(thread_ap_block_pp0_stage1);

    SC_METHOD(thread_ap_block_pp0_stage1_00001);

    SC_METHOD(thread_ap_block_pp0_stage1_11001);

    SC_METHOD(thread_ap_block_pp0_stage1_subdone);

    SC_METHOD(thread_ap_block_pp0_stage2);

    SC_METHOD(thread_ap_block_pp0_stage2_00001);

    SC_METHOD(thread_ap_block_pp0_stage2_11001);

    SC_METHOD(thread_ap_block_pp0_stage2_subdone);

    SC_METHOD(thread_ap_block_pp0_stage3);

    SC_METHOD(thread_ap_block_pp0_stage3_00001);

    SC_METHOD(thread_ap_block_pp0_stage3_11001);

    SC_METHOD(thread_ap_block_pp0_stage3_subdone);

    SC_METHOD(thread_ap_block_pp0_stage4);

    SC_METHOD(thread_ap_block_pp0_stage4_11001);

    SC_METHOD(thread_ap_block_pp0_stage4_subdone);

    SC_METHOD(thread_ap_block_state15_pp0_stage0_iter0);

    SC_METHOD(thread_ap_block_state16_pp0_stage1_iter0);

    SC_METHOD(thread_ap_block_state17_pp0_stage2_iter0);

    SC_METHOD(thread_ap_block_state18_pp0_stage3_iter0);

    SC_METHOD(thread_ap_block_state19_pp0_stage4_iter0);

    SC_METHOD(thread_ap_block_state20_pp0_stage0_iter1);

    SC_METHOD(thread_ap_block_state21_pp0_stage1_iter1);

    SC_METHOD(thread_ap_block_state22_pp0_stage2_iter1);

    SC_METHOD(thread_ap_block_state23_pp0_stage3_iter1);

    SC_METHOD(thread_ap_block_state24_pp0_stage4_iter1);

    SC_METHOD(thread_ap_block_state25_pp0_stage0_iter2);

    SC_METHOD(thread_ap_block_state26_pp0_stage1_iter2);

    SC_METHOD(thread_ap_block_state27_pp0_stage2_iter2);

    SC_METHOD(thread_ap_block_state28_pp0_stage3_iter2);

    SC_METHOD(thread_ap_block_state29_pp0_stage4_iter2);

    SC_METHOD(thread_ap_block_state30_pp0_stage0_iter3);

    SC_METHOD(thread_ap_block_state31_pp0_stage1_iter3);

    SC_METHOD(thread_ap_block_state32_pp0_stage2_iter3);

    SC_METHOD(thread_ap_block_state33_pp0_stage3_iter3);

    SC_METHOD(thread_ap_block_state34_pp0_stage4_iter3);

    SC_METHOD(thread_ap_block_state35_pp0_stage0_iter4);

    SC_METHOD(thread_ap_block_state36_pp0_stage1_iter4);

    SC_METHOD(thread_ap_block_state37_pp0_stage2_iter4);

    SC_METHOD(thread_ap_block_state38_pp0_stage3_iter4);

    SC_METHOD(thread_ap_block_state39_pp0_stage4_iter4);

    SC_METHOD(thread_ap_block_state40_pp0_stage0_iter5);

    SC_METHOD(thread_ap_block_state41_pp0_stage1_iter5);

    SC_METHOD(thread_ap_block_state42_pp0_stage2_iter5);

    SC_METHOD(thread_ap_block_state43_pp0_stage3_iter5);

    SC_METHOD(thread_ap_block_state44_pp0_stage4_iter5);

    SC_METHOD(thread_ap_block_state45_pp0_stage0_iter6);

    SC_METHOD(thread_ap_block_state46_pp0_stage1_iter6);

    SC_METHOD(thread_ap_block_state47_pp0_stage2_iter6);

    SC_METHOD(thread_ap_block_state48_pp0_stage3_iter6);

    SC_METHOD(thread_ap_block_state49_pp0_stage4_iter6);

    SC_METHOD(thread_ap_block_state50_pp0_stage0_iter7);

    SC_METHOD(thread_ap_block_state51_pp0_stage1_iter7);

    SC_METHOD(thread_ap_block_state52_pp0_stage2_iter7);

    SC_METHOD(thread_ap_block_state53_pp0_stage3_iter7);

    SC_METHOD(thread_ap_block_state54_pp0_stage4_iter7);

    SC_METHOD(thread_ap_block_state55_pp0_stage0_iter8);

    SC_METHOD(thread_ap_block_state56_pp0_stage1_iter8);

    SC_METHOD(thread_ap_condition_445);
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage4 );

    SC_METHOD(thread_ap_condition_449);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter2 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_condition_pp0_exit_iter0_state15);
    sensitive << ( icmp_ln27_fu_290_p2 );

    SC_METHOD(thread_ap_done);
    sensitive << ( ap_CS_fsm_state58 );
    sensitive << ( icmp_ln40_fu_327_p2 );

    SC_METHOD(thread_ap_enable_pp0);
    sensitive << ( ap_idle_pp0 );

    SC_METHOD(thread_ap_idle);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm_state1 );

    SC_METHOD(thread_ap_idle_pp0);
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_enable_reg_pp0_iter3 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_enable_reg_pp0_iter2 );

    SC_METHOD(thread_ap_phi_mux_empty_41_phi_fu_176_p4);
    sensitive << ( empty_41_reg_172 );
    sensitive << ( icmp_ln27_reg_383_pp0_iter8_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( tmp_12_reg_493 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_ap_phi_mux_empty_42_phi_fu_188_p4);
    sensitive << ( empty_42_reg_184 );
    sensitive << ( icmp_ln27_reg_383_pp0_iter7_reg );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( tmp_8_reg_487 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_ap_phi_mux_j_0_phi_fu_200_p4);
    sensitive << ( j_0_reg_196 );
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln27_reg_383 );
    sensitive << ( j_reg_387 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_ap_ready);
    sensitive << ( ap_CS_fsm_state58 );
    sensitive << ( icmp_ln40_fu_327_p2 );

    SC_METHOD(thread_bitcast_ln30_1_fu_322_p1);
    sensitive << ( xor_ln30_fu_316_p2 );

    SC_METHOD(thread_bitcast_ln30_fu_313_p1);
    sensitive << ( tmp_i_i9_reg_417 );

    SC_METHOD(thread_grp_fu_239_opcode);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( icmp_ln27_reg_383_pp0_iter5_reg );
    sensitive << ( icmp_ln27_reg_383_pp0_iter6_reg );
    sensitive << ( icmp_ln27_reg_383_pp0_iter7_reg );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_block_pp0_stage0_00001 );
    sensitive << ( ap_block_pp0_stage3_00001 );
    sensitive << ( ap_block_pp0_stage1_00001 );
    sensitive << ( ap_block_pp0_stage2_00001 );

    SC_METHOD(thread_grp_fu_239_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( tmp_9_reg_457 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_5_reg_467 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_phi_mux_empty_41_phi_fu_176_p4 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_phi_mux_empty_42_phi_fu_188_p4 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_239_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( tmp_s_reg_462 );
    sensitive << ( tmp_10_reg_472 );
    sensitive << ( tmp_1_reg_477 );
    sensitive << ( ap_enable_reg_pp0_iter6 );
    sensitive << ( tmp_11_reg_482 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_245_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( tmp_3_reg_397 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( sample_real_load_reg_442 );
    sensitive << ( sample_imag_load_reg_447 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_245_p1);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( w_reg_378 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_CS_fsm_pp0_stage2 );
    sensitive << ( ap_CS_fsm_pp0_stage4 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( c_reg_432 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( s_reg_452 );
    sensitive << ( ap_enable_reg_pp0_iter5 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage4 );
    sensitive << ( ap_block_pp0_stage2 );

    SC_METHOD(thread_grp_fu_249_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_j_0_phi_fu_200_p4 );
    sensitive << ( ap_block_pp0_stage0 );

    SC_METHOD(thread_grp_fu_252_p0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( tmp_2_reg_363 );
    sensitive << ( tmp_i_i_reg_412 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( bitcast_ln30_1_fu_322_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state13 );

    SC_METHOD(thread_grp_fu_264_p0);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_160 );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_219_ap_start);
    sensitive << ( grp_sin_or_cos_double_s_fu_219_ap_start_reg );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_219_do_cos);
    sensitive << ( icmp_ln27_reg_383_pp0_iter1_reg );
    sensitive << ( ap_condition_445 );
    sensitive << ( ap_condition_449 );

    SC_METHOD(thread_grp_sin_or_cos_double_s_fu_219_t_in);
    sensitive << ( icmp_ln27_reg_383_pp0_iter1_reg );
    sensitive << ( grp_fu_255_p1 );
    sensitive << ( x_assign_reg_407 );
    sensitive << ( ap_condition_445 );
    sensitive << ( ap_condition_449 );

    SC_METHOD(thread_i_2_fu_273_p2);
    sensitive << ( i_0_reg_160 );

    SC_METHOD(thread_i_fu_333_p2);
    sensitive << ( i_1_reg_208 );

    SC_METHOD(thread_icmp_ln18_fu_267_p2);
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( i_0_reg_160 );

    SC_METHOD(thread_icmp_ln27_fu_290_p2);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_phi_mux_j_0_phi_fu_200_p4 );

    SC_METHOD(thread_icmp_ln40_fu_327_p2);
    sensitive << ( ap_CS_fsm_state58 );
    sensitive << ( i_1_reg_208 );

    SC_METHOD(thread_j_fu_296_p2);
    sensitive << ( ap_phi_mux_j_0_phi_fu_200_p4 );

    SC_METHOD(thread_sample_imag_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( zext_ln41_reg_507 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state59 );
    sensitive << ( zext_ln34_fu_307_p1 );

    SC_METHOD(thread_sample_imag_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_CS_fsm_state59 );

    SC_METHOD(thread_sample_imag_d0);
    sensitive << ( temp_imag_q0 );
    sensitive << ( ap_CS_fsm_state59 );

    SC_METHOD(thread_sample_imag_we0);
    sensitive << ( ap_CS_fsm_state59 );

    SC_METHOD(thread_sample_real_address0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( zext_ln41_reg_507 );
    sensitive << ( ap_block_pp0_stage0 );
    sensitive << ( ap_CS_fsm_state59 );
    sensitive << ( zext_ln34_fu_307_p1 );

    SC_METHOD(thread_sample_real_ce0);
    sensitive << ( ap_CS_fsm_pp0_stage0 );
    sensitive << ( ap_block_pp0_stage0_11001 );
    sensitive << ( ap_enable_reg_pp0_iter4 );
    sensitive << ( ap_CS_fsm_state59 );

    SC_METHOD(thread_sample_real_d0);
    sensitive << ( temp_real_q0 );
    sensitive << ( ap_CS_fsm_state59 );

    SC_METHOD(thread_sample_real_we0);
    sensitive << ( ap_CS_fsm_state59 );

    SC_METHOD(thread_temp_imag_address0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( temp_imag_addr_reg_373 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_CS_fsm_state58 );
    sensitive << ( zext_ln41_fu_339_p1 );
    sensitive << ( ap_block_pp0_stage1 );
    sensitive << ( zext_ln19_fu_284_p1 );

    SC_METHOD(thread_temp_imag_ce0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_CS_fsm_state58 );

    SC_METHOD(thread_temp_imag_d0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( tmp_12_reg_493 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_block_pp0_stage1 );

    SC_METHOD(thread_temp_imag_we0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln27_reg_383_pp0_iter8_reg );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_block_pp0_stage1_11001 );
    sensitive << ( ap_enable_reg_pp0_iter8 );

    SC_METHOD(thread_temp_real_address0);
    sensitive << ( temp_real_addr_reg_368 );
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_CS_fsm_state58 );
    sensitive << ( zext_ln41_fu_339_p1 );
    sensitive << ( ap_block_pp0_stage3 );
    sensitive << ( zext_ln19_fu_284_p1 );

    SC_METHOD(thread_temp_real_ce0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_CS_fsm_state58 );

    SC_METHOD(thread_temp_real_d0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( tmp_8_reg_487 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_block_pp0_stage3 );

    SC_METHOD(thread_temp_real_we0);
    sensitive << ( ap_CS_fsm_state14 );
    sensitive << ( icmp_ln27_reg_383_pp0_iter7_reg );
    sensitive << ( ap_CS_fsm_pp0_stage3 );
    sensitive << ( ap_block_pp0_stage3_11001 );
    sensitive << ( ap_enable_reg_pp0_iter7 );

    SC_METHOD(thread_xor_ln30_fu_316_p2);
    sensitive << ( bitcast_ln30_fu_313_p1 );

    SC_METHOD(thread_zext_ln19_fu_284_p1);
    sensitive << ( i_0_reg_160 );

    SC_METHOD(thread_zext_ln34_fu_307_p1);
    sensitive << ( j_0_reg_196_pp0_iter3_reg );

    SC_METHOD(thread_zext_ln41_fu_339_p1);
    sensitive << ( i_1_reg_208 );

    SC_METHOD(thread_ap_NS_fsm);
    sensitive << ( ap_start );
    sensitive << ( ap_CS_fsm );
    sensitive << ( ap_CS_fsm_state1 );
    sensitive << ( ap_CS_fsm_state2 );
    sensitive << ( icmp_ln18_fu_267_p2 );
    sensitive << ( icmp_ln27_fu_290_p2 );
    sensitive << ( ap_enable_reg_pp0_iter0 );
    sensitive << ( ap_enable_reg_pp0_iter1 );
    sensitive << ( ap_CS_fsm_pp0_stage1 );
    sensitive << ( ap_enable_reg_pp0_iter7 );
    sensitive << ( ap_enable_reg_pp0_iter8 );
    sensitive << ( ap_CS_fsm_state58 );
    sensitive << ( icmp_ln40_fu_327_p2 );
    sensitive << ( ap_block_pp0_stage0_subdone );
    sensitive << ( ap_block_pp0_stage4_subdone );
    sensitive << ( ap_block_pp0_stage1_subdone );
    sensitive << ( ap_block_pp0_stage2_subdone );
    sensitive << ( ap_block_pp0_stage3_subdone );

    SC_THREAD(thread_hdltv_gen);
    sensitive << ( ap_clk.pos() );

    SC_THREAD(thread_ap_var_for_const0);

    SC_THREAD(thread_ap_var_for_const1);

    ap_CS_fsm = "0000000000000000000001";
    ap_enable_reg_pp0_iter0 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter1 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter3 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter4 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter5 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter6 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter7 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter8 = SC_LOGIC_0;
    ap_enable_reg_pp0_iter2 = SC_LOGIC_0;
    grp_sin_or_cos_double_s_fu_219_ap_start_reg = SC_LOGIC_0;
    static int apTFileNum = 0;
    stringstream apTFilenSS;
    apTFilenSS << "dft_sc_trace_" << apTFileNum ++;
    string apTFn = apTFilenSS.str();
    mVcdFile = sc_create_vcd_trace_file(apTFn.c_str());
    mVcdFile->set_time_unit(1, SC_PS);
    if (1) {
#ifdef __HLS_TRACE_LEVEL_PORT__
    sc_trace(mVcdFile, ap_clk, "(port)ap_clk");
    sc_trace(mVcdFile, ap_rst, "(port)ap_rst");
    sc_trace(mVcdFile, ap_start, "(port)ap_start");
    sc_trace(mVcdFile, ap_done, "(port)ap_done");
    sc_trace(mVcdFile, ap_idle, "(port)ap_idle");
    sc_trace(mVcdFile, ap_ready, "(port)ap_ready");
    sc_trace(mVcdFile, sample_real_address0, "(port)sample_real_address0");
    sc_trace(mVcdFile, sample_real_ce0, "(port)sample_real_ce0");
    sc_trace(mVcdFile, sample_real_we0, "(port)sample_real_we0");
    sc_trace(mVcdFile, sample_real_d0, "(port)sample_real_d0");
    sc_trace(mVcdFile, sample_real_q0, "(port)sample_real_q0");
    sc_trace(mVcdFile, sample_imag_address0, "(port)sample_imag_address0");
    sc_trace(mVcdFile, sample_imag_ce0, "(port)sample_imag_ce0");
    sc_trace(mVcdFile, sample_imag_we0, "(port)sample_imag_we0");
    sc_trace(mVcdFile, sample_imag_d0, "(port)sample_imag_d0");
    sc_trace(mVcdFile, sample_imag_q0, "(port)sample_imag_q0");
#endif
#ifdef __HLS_TRACE_LEVEL_INT__
    sc_trace(mVcdFile, ap_CS_fsm, "ap_CS_fsm");
    sc_trace(mVcdFile, ap_CS_fsm_state1, "ap_CS_fsm_state1");
    sc_trace(mVcdFile, empty_41_reg_172, "empty_41_reg_172");
    sc_trace(mVcdFile, empty_42_reg_184, "empty_42_reg_184");
    sc_trace(mVcdFile, j_0_reg_196, "j_0_reg_196");
    sc_trace(mVcdFile, j_0_reg_196_pp0_iter1_reg, "j_0_reg_196_pp0_iter1_reg");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage0, "ap_CS_fsm_pp0_stage0");
    sc_trace(mVcdFile, ap_block_state15_pp0_stage0_iter0, "ap_block_state15_pp0_stage0_iter0");
    sc_trace(mVcdFile, ap_block_state20_pp0_stage0_iter1, "ap_block_state20_pp0_stage0_iter1");
    sc_trace(mVcdFile, ap_block_state25_pp0_stage0_iter2, "ap_block_state25_pp0_stage0_iter2");
    sc_trace(mVcdFile, ap_block_state30_pp0_stage0_iter3, "ap_block_state30_pp0_stage0_iter3");
    sc_trace(mVcdFile, ap_block_state35_pp0_stage0_iter4, "ap_block_state35_pp0_stage0_iter4");
    sc_trace(mVcdFile, ap_block_state40_pp0_stage0_iter5, "ap_block_state40_pp0_stage0_iter5");
    sc_trace(mVcdFile, ap_block_state45_pp0_stage0_iter6, "ap_block_state45_pp0_stage0_iter6");
    sc_trace(mVcdFile, ap_block_state50_pp0_stage0_iter7, "ap_block_state50_pp0_stage0_iter7");
    sc_trace(mVcdFile, ap_block_state55_pp0_stage0_iter8, "ap_block_state55_pp0_stage0_iter8");
    sc_trace(mVcdFile, ap_block_pp0_stage0_11001, "ap_block_pp0_stage0_11001");
    sc_trace(mVcdFile, j_0_reg_196_pp0_iter2_reg, "j_0_reg_196_pp0_iter2_reg");
    sc_trace(mVcdFile, j_0_reg_196_pp0_iter3_reg, "j_0_reg_196_pp0_iter3_reg");
    sc_trace(mVcdFile, i_2_fu_273_p2, "i_2_fu_273_p2");
    sc_trace(mVcdFile, i_2_reg_348, "i_2_reg_348");
    sc_trace(mVcdFile, ap_CS_fsm_state2, "ap_CS_fsm_state2");
    sc_trace(mVcdFile, icmp_ln18_fu_267_p2, "icmp_ln18_fu_267_p2");
    sc_trace(mVcdFile, grp_fu_264_p1, "grp_fu_264_p1");
    sc_trace(mVcdFile, tmp_reg_358, "tmp_reg_358");
    sc_trace(mVcdFile, ap_CS_fsm_state6, "ap_CS_fsm_state6");
    sc_trace(mVcdFile, grp_fu_259_p2, "grp_fu_259_p2");
    sc_trace(mVcdFile, tmp_2_reg_363, "tmp_2_reg_363");
    sc_trace(mVcdFile, ap_CS_fsm_state12, "ap_CS_fsm_state12");
    sc_trace(mVcdFile, temp_real_addr_reg_368, "temp_real_addr_reg_368");
    sc_trace(mVcdFile, ap_CS_fsm_state14, "ap_CS_fsm_state14");
    sc_trace(mVcdFile, temp_imag_addr_reg_373, "temp_imag_addr_reg_373");
    sc_trace(mVcdFile, grp_fu_252_p1, "grp_fu_252_p1");
    sc_trace(mVcdFile, w_reg_378, "w_reg_378");
    sc_trace(mVcdFile, icmp_ln27_fu_290_p2, "icmp_ln27_fu_290_p2");
    sc_trace(mVcdFile, icmp_ln27_reg_383, "icmp_ln27_reg_383");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter1_reg, "icmp_ln27_reg_383_pp0_iter1_reg");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter2_reg, "icmp_ln27_reg_383_pp0_iter2_reg");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter3_reg, "icmp_ln27_reg_383_pp0_iter3_reg");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter4_reg, "icmp_ln27_reg_383_pp0_iter4_reg");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter5_reg, "icmp_ln27_reg_383_pp0_iter5_reg");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter6_reg, "icmp_ln27_reg_383_pp0_iter6_reg");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter7_reg, "icmp_ln27_reg_383_pp0_iter7_reg");
    sc_trace(mVcdFile, icmp_ln27_reg_383_pp0_iter8_reg, "icmp_ln27_reg_383_pp0_iter8_reg");
    sc_trace(mVcdFile, j_fu_296_p2, "j_fu_296_p2");
    sc_trace(mVcdFile, j_reg_387, "j_reg_387");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter0, "ap_enable_reg_pp0_iter0");
    sc_trace(mVcdFile, grp_fu_249_p1, "grp_fu_249_p1");
    sc_trace(mVcdFile, tmp_3_reg_397, "tmp_3_reg_397");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage3, "ap_CS_fsm_pp0_stage3");
    sc_trace(mVcdFile, ap_block_state18_pp0_stage3_iter0, "ap_block_state18_pp0_stage3_iter0");
    sc_trace(mVcdFile, ap_block_state23_pp0_stage3_iter1, "ap_block_state23_pp0_stage3_iter1");
    sc_trace(mVcdFile, ap_block_state28_pp0_stage3_iter2, "ap_block_state28_pp0_stage3_iter2");
    sc_trace(mVcdFile, ap_block_state33_pp0_stage3_iter3, "ap_block_state33_pp0_stage3_iter3");
    sc_trace(mVcdFile, ap_block_state38_pp0_stage3_iter4, "ap_block_state38_pp0_stage3_iter4");
    sc_trace(mVcdFile, ap_block_state43_pp0_stage3_iter5, "ap_block_state43_pp0_stage3_iter5");
    sc_trace(mVcdFile, ap_block_state48_pp0_stage3_iter6, "ap_block_state48_pp0_stage3_iter6");
    sc_trace(mVcdFile, ap_block_state53_pp0_stage3_iter7, "ap_block_state53_pp0_stage3_iter7");
    sc_trace(mVcdFile, ap_block_pp0_stage3_11001, "ap_block_pp0_stage3_11001");
    sc_trace(mVcdFile, grp_fu_245_p2, "grp_fu_245_p2");
    sc_trace(mVcdFile, tmp_4_reg_402, "tmp_4_reg_402");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage2, "ap_CS_fsm_pp0_stage2");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter1, "ap_enable_reg_pp0_iter1");
    sc_trace(mVcdFile, ap_block_state17_pp0_stage2_iter0, "ap_block_state17_pp0_stage2_iter0");
    sc_trace(mVcdFile, ap_block_state22_pp0_stage2_iter1, "ap_block_state22_pp0_stage2_iter1");
    sc_trace(mVcdFile, ap_block_state27_pp0_stage2_iter2, "ap_block_state27_pp0_stage2_iter2");
    sc_trace(mVcdFile, ap_block_state32_pp0_stage2_iter3, "ap_block_state32_pp0_stage2_iter3");
    sc_trace(mVcdFile, ap_block_state37_pp0_stage2_iter4, "ap_block_state37_pp0_stage2_iter4");
    sc_trace(mVcdFile, ap_block_state42_pp0_stage2_iter5, "ap_block_state42_pp0_stage2_iter5");
    sc_trace(mVcdFile, ap_block_state47_pp0_stage2_iter6, "ap_block_state47_pp0_stage2_iter6");
    sc_trace(mVcdFile, ap_block_state52_pp0_stage2_iter7, "ap_block_state52_pp0_stage2_iter7");
    sc_trace(mVcdFile, ap_block_pp0_stage2_11001, "ap_block_pp0_stage2_11001");
    sc_trace(mVcdFile, grp_fu_255_p1, "grp_fu_255_p1");
    sc_trace(mVcdFile, x_assign_reg_407, "x_assign_reg_407");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage4, "ap_CS_fsm_pp0_stage4");
    sc_trace(mVcdFile, ap_block_state19_pp0_stage4_iter0, "ap_block_state19_pp0_stage4_iter0");
    sc_trace(mVcdFile, ap_block_state24_pp0_stage4_iter1, "ap_block_state24_pp0_stage4_iter1");
    sc_trace(mVcdFile, ap_block_state29_pp0_stage4_iter2, "ap_block_state29_pp0_stage4_iter2");
    sc_trace(mVcdFile, ap_block_state34_pp0_stage4_iter3, "ap_block_state34_pp0_stage4_iter3");
    sc_trace(mVcdFile, ap_block_state39_pp0_stage4_iter4, "ap_block_state39_pp0_stage4_iter4");
    sc_trace(mVcdFile, ap_block_state44_pp0_stage4_iter5, "ap_block_state44_pp0_stage4_iter5");
    sc_trace(mVcdFile, ap_block_state49_pp0_stage4_iter6, "ap_block_state49_pp0_stage4_iter6");
    sc_trace(mVcdFile, ap_block_state54_pp0_stage4_iter7, "ap_block_state54_pp0_stage4_iter7");
    sc_trace(mVcdFile, ap_block_pp0_stage4_11001, "ap_block_pp0_stage4_11001");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_ap_return, "grp_sin_or_cos_double_s_fu_219_ap_return");
    sc_trace(mVcdFile, tmp_i_i_reg_412, "tmp_i_i_reg_412");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter3, "ap_enable_reg_pp0_iter3");
    sc_trace(mVcdFile, tmp_i_i9_reg_417, "tmp_i_i9_reg_417");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter4, "ap_enable_reg_pp0_iter4");
    sc_trace(mVcdFile, c_reg_432, "c_reg_432");
    sc_trace(mVcdFile, ap_CS_fsm_pp0_stage1, "ap_CS_fsm_pp0_stage1");
    sc_trace(mVcdFile, ap_block_state16_pp0_stage1_iter0, "ap_block_state16_pp0_stage1_iter0");
    sc_trace(mVcdFile, ap_block_state21_pp0_stage1_iter1, "ap_block_state21_pp0_stage1_iter1");
    sc_trace(mVcdFile, ap_block_state26_pp0_stage1_iter2, "ap_block_state26_pp0_stage1_iter2");
    sc_trace(mVcdFile, ap_block_state31_pp0_stage1_iter3, "ap_block_state31_pp0_stage1_iter3");
    sc_trace(mVcdFile, ap_block_state36_pp0_stage1_iter4, "ap_block_state36_pp0_stage1_iter4");
    sc_trace(mVcdFile, ap_block_state41_pp0_stage1_iter5, "ap_block_state41_pp0_stage1_iter5");
    sc_trace(mVcdFile, ap_block_state46_pp0_stage1_iter6, "ap_block_state46_pp0_stage1_iter6");
    sc_trace(mVcdFile, ap_block_state51_pp0_stage1_iter7, "ap_block_state51_pp0_stage1_iter7");
    sc_trace(mVcdFile, ap_block_state56_pp0_stage1_iter8, "ap_block_state56_pp0_stage1_iter8");
    sc_trace(mVcdFile, ap_block_pp0_stage1_11001, "ap_block_pp0_stage1_11001");
    sc_trace(mVcdFile, bitcast_ln30_1_fu_322_p1, "bitcast_ln30_1_fu_322_p1");
    sc_trace(mVcdFile, sample_real_load_reg_442, "sample_real_load_reg_442");
    sc_trace(mVcdFile, sample_imag_load_reg_447, "sample_imag_load_reg_447");
    sc_trace(mVcdFile, s_reg_452, "s_reg_452");
    sc_trace(mVcdFile, tmp_9_reg_457, "tmp_9_reg_457");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter5, "ap_enable_reg_pp0_iter5");
    sc_trace(mVcdFile, tmp_s_reg_462, "tmp_s_reg_462");
    sc_trace(mVcdFile, tmp_5_reg_467, "tmp_5_reg_467");
    sc_trace(mVcdFile, tmp_10_reg_472, "tmp_10_reg_472");
    sc_trace(mVcdFile, grp_fu_239_p2, "grp_fu_239_p2");
    sc_trace(mVcdFile, tmp_1_reg_477, "tmp_1_reg_477");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter6, "ap_enable_reg_pp0_iter6");
    sc_trace(mVcdFile, tmp_11_reg_482, "tmp_11_reg_482");
    sc_trace(mVcdFile, tmp_8_reg_487, "tmp_8_reg_487");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter7, "ap_enable_reg_pp0_iter7");
    sc_trace(mVcdFile, tmp_12_reg_493, "tmp_12_reg_493");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter8, "ap_enable_reg_pp0_iter8");
    sc_trace(mVcdFile, i_fu_333_p2, "i_fu_333_p2");
    sc_trace(mVcdFile, i_reg_502, "i_reg_502");
    sc_trace(mVcdFile, ap_CS_fsm_state58, "ap_CS_fsm_state58");
    sc_trace(mVcdFile, zext_ln41_fu_339_p1, "zext_ln41_fu_339_p1");
    sc_trace(mVcdFile, zext_ln41_reg_507, "zext_ln41_reg_507");
    sc_trace(mVcdFile, icmp_ln40_fu_327_p2, "icmp_ln40_fu_327_p2");
    sc_trace(mVcdFile, ap_block_pp0_stage0_subdone, "ap_block_pp0_stage0_subdone");
    sc_trace(mVcdFile, ap_condition_pp0_exit_iter0_state15, "ap_condition_pp0_exit_iter0_state15");
    sc_trace(mVcdFile, ap_block_pp0_stage4_subdone, "ap_block_pp0_stage4_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage1_subdone, "ap_block_pp0_stage1_subdone");
    sc_trace(mVcdFile, ap_enable_reg_pp0_iter2, "ap_enable_reg_pp0_iter2");
    sc_trace(mVcdFile, temp_real_address0, "temp_real_address0");
    sc_trace(mVcdFile, temp_real_ce0, "temp_real_ce0");
    sc_trace(mVcdFile, temp_real_we0, "temp_real_we0");
    sc_trace(mVcdFile, temp_real_d0, "temp_real_d0");
    sc_trace(mVcdFile, temp_real_q0, "temp_real_q0");
    sc_trace(mVcdFile, temp_imag_address0, "temp_imag_address0");
    sc_trace(mVcdFile, temp_imag_ce0, "temp_imag_ce0");
    sc_trace(mVcdFile, temp_imag_we0, "temp_imag_we0");
    sc_trace(mVcdFile, temp_imag_d0, "temp_imag_d0");
    sc_trace(mVcdFile, temp_imag_q0, "temp_imag_q0");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_ap_start, "grp_sin_or_cos_double_s_fu_219_ap_start");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_ap_done, "grp_sin_or_cos_double_s_fu_219_ap_done");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_ap_idle, "grp_sin_or_cos_double_s_fu_219_ap_idle");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_ap_ready, "grp_sin_or_cos_double_s_fu_219_ap_ready");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_t_in, "grp_sin_or_cos_double_s_fu_219_t_in");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_do_cos, "grp_sin_or_cos_double_s_fu_219_do_cos");
    sc_trace(mVcdFile, i_0_reg_160, "i_0_reg_160");
    sc_trace(mVcdFile, ap_CS_fsm_state57, "ap_CS_fsm_state57");
    sc_trace(mVcdFile, ap_phi_mux_empty_41_phi_fu_176_p4, "ap_phi_mux_empty_41_phi_fu_176_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage1, "ap_block_pp0_stage1");
    sc_trace(mVcdFile, ap_phi_mux_empty_42_phi_fu_188_p4, "ap_phi_mux_empty_42_phi_fu_188_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage3, "ap_block_pp0_stage3");
    sc_trace(mVcdFile, ap_phi_mux_j_0_phi_fu_200_p4, "ap_phi_mux_j_0_phi_fu_200_p4");
    sc_trace(mVcdFile, ap_block_pp0_stage0, "ap_block_pp0_stage0");
    sc_trace(mVcdFile, i_1_reg_208, "i_1_reg_208");
    sc_trace(mVcdFile, ap_CS_fsm_state59, "ap_CS_fsm_state59");
    sc_trace(mVcdFile, grp_sin_or_cos_double_s_fu_219_ap_start_reg, "grp_sin_or_cos_double_s_fu_219_ap_start_reg");
    sc_trace(mVcdFile, ap_block_pp0_stage4, "ap_block_pp0_stage4");
    sc_trace(mVcdFile, ap_block_pp0_stage2, "ap_block_pp0_stage2");
    sc_trace(mVcdFile, zext_ln19_fu_284_p1, "zext_ln19_fu_284_p1");
    sc_trace(mVcdFile, zext_ln34_fu_307_p1, "zext_ln34_fu_307_p1");
    sc_trace(mVcdFile, grp_fu_239_p0, "grp_fu_239_p0");
    sc_trace(mVcdFile, grp_fu_239_p1, "grp_fu_239_p1");
    sc_trace(mVcdFile, grp_fu_245_p0, "grp_fu_245_p0");
    sc_trace(mVcdFile, grp_fu_245_p1, "grp_fu_245_p1");
    sc_trace(mVcdFile, grp_fu_249_p0, "grp_fu_249_p0");
    sc_trace(mVcdFile, grp_fu_252_p0, "grp_fu_252_p0");
    sc_trace(mVcdFile, ap_CS_fsm_state13, "ap_CS_fsm_state13");
    sc_trace(mVcdFile, ap_CS_fsm_state7, "ap_CS_fsm_state7");
    sc_trace(mVcdFile, grp_fu_264_p0, "grp_fu_264_p0");
    sc_trace(mVcdFile, bitcast_ln30_fu_313_p1, "bitcast_ln30_fu_313_p1");
    sc_trace(mVcdFile, xor_ln30_fu_316_p2, "xor_ln30_fu_316_p2");
    sc_trace(mVcdFile, grp_fu_239_opcode, "grp_fu_239_opcode");
    sc_trace(mVcdFile, ap_block_pp0_stage0_00001, "ap_block_pp0_stage0_00001");
    sc_trace(mVcdFile, ap_block_pp0_stage3_00001, "ap_block_pp0_stage3_00001");
    sc_trace(mVcdFile, ap_block_pp0_stage1_00001, "ap_block_pp0_stage1_00001");
    sc_trace(mVcdFile, ap_block_pp0_stage2_00001, "ap_block_pp0_stage2_00001");
    sc_trace(mVcdFile, ap_NS_fsm, "ap_NS_fsm");
    sc_trace(mVcdFile, ap_block_pp0_stage2_subdone, "ap_block_pp0_stage2_subdone");
    sc_trace(mVcdFile, ap_block_pp0_stage3_subdone, "ap_block_pp0_stage3_subdone");
    sc_trace(mVcdFile, ap_idle_pp0, "ap_idle_pp0");
    sc_trace(mVcdFile, ap_enable_pp0, "ap_enable_pp0");
    sc_trace(mVcdFile, ap_condition_445, "ap_condition_445");
    sc_trace(mVcdFile, ap_condition_449, "ap_condition_449");
#endif

    }
    mHdltvinHandle.open("dft.hdltvin.dat");
    mHdltvoutHandle.open("dft.hdltvout.dat");
}

dft::~dft() {
    if (mVcdFile) 
        sc_close_vcd_trace_file(mVcdFile);

    mHdltvinHandle << "] " << endl;
    mHdltvoutHandle << "] " << endl;
    mHdltvinHandle.close();
    mHdltvoutHandle.close();
    delete temp_real_U;
    delete temp_imag_U;
    delete grp_sin_or_cos_double_s_fu_219;
    delete dft_faddfsub_32nsibs_U17;
    delete dft_fmul_32ns_32njbC_U18;
    delete dft_sitofp_32ns_3kbM_U19;
    delete dft_fptrunc_64ns_lbW_U20;
    delete dft_fpext_32ns_64mb6_U21;
    delete dft_dmul_64ns_64nncg_U22;
    delete dft_sitodp_32ns_6ocq_U23;
}

void dft::thread_ap_var_for_const0() {
    ap_var_for_const0 = ap_const_logic_1;
}

void dft::thread_ap_var_for_const1() {
    ap_var_for_const1 = ap_const_lv64_3F9921FB5444261E;
}

void dft::thread_ap_clk_no_reset_() {
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_CS_fsm = ap_ST_fsm_state1;
    } else {
        ap_CS_fsm = ap_NS_fsm.read();
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter0 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && 
             esl_seteq<1,1,1>(ap_const_logic_1, ap_condition_pp0_exit_iter0_state15.read()))) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_0;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
            ap_enable_reg_pp0_iter0 = ap_const_logic_1;
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter1 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter1 = ap_enable_reg_pp0_iter0.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter2 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter2 = ap_enable_reg_pp0_iter1.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter3 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter3 = ap_enable_reg_pp0_iter2.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter4 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter4 = ap_enable_reg_pp0_iter3.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter5 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter5 = ap_enable_reg_pp0_iter4.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter6 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter6 = ap_enable_reg_pp0_iter5.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter7 = ap_const_logic_0;
    } else {
        if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
             esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0))) {
            ap_enable_reg_pp0_iter7 = ap_enable_reg_pp0_iter6.read();
        }
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        ap_enable_reg_pp0_iter8 = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0)))) {
            ap_enable_reg_pp0_iter8 = ap_enable_reg_pp0_iter7.read();
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
            ap_enable_reg_pp0_iter8 = ap_const_logic_0;
        }
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter8_reg.read()))) {
        empty_41_reg_172 = tmp_12_reg_493.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        empty_41_reg_172 = ap_const_lv32_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter7_reg.read()))) {
        empty_42_reg_184 = tmp_8_reg_487.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        empty_42_reg_184 = ap_const_lv32_0;
    }
    if ( ap_rst.read() == ap_const_logic_1) {
        grp_sin_or_cos_double_s_fu_219_ap_start_reg = ap_const_logic_0;
    } else {
        if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter1_reg.read())) || 
             (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
              esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter1_reg.read()) && 
              esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
              esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0)))) {
            grp_sin_or_cos_double_s_fu_219_ap_start_reg = ap_const_logic_1;
        } else if (esl_seteq<1,1,1>(ap_const_logic_1, grp_sin_or_cos_double_s_fu_219_ap_ready.read())) {
            grp_sin_or_cos_double_s_fu_219_ap_start_reg = ap_const_logic_0;
        }
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state57.read())) {
        i_0_reg_160 = i_2_reg_348.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && 
                esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
        i_0_reg_160 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && 
         esl_seteq<1,1,1>(icmp_ln18_fu_267_p2.read(), ap_const_lv1_1))) {
        i_1_reg_208 = ap_const_lv9_0;
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read())) {
        i_1_reg_208 = i_reg_502.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()))) {
        j_0_reg_196 = j_reg_387.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        j_0_reg_196 = ap_const_lv9_0;
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter4_reg.read()))) {
        c_reg_432 = grp_fu_252_p1.read();
        sample_imag_load_reg_447 = sample_imag_q0.read();
        sample_real_load_reg_442 = sample_real_q0.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read())) {
        i_2_reg_348 = i_2_fu_273_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read())) {
        i_reg_502 = i_fu_333_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0))) {
        icmp_ln27_reg_383 = icmp_ln27_fu_290_p2.read();
        icmp_ln27_reg_383_pp0_iter1_reg = icmp_ln27_reg_383.read();
        icmp_ln27_reg_383_pp0_iter2_reg = icmp_ln27_reg_383_pp0_iter1_reg.read();
        icmp_ln27_reg_383_pp0_iter3_reg = icmp_ln27_reg_383_pp0_iter2_reg.read();
        icmp_ln27_reg_383_pp0_iter4_reg = icmp_ln27_reg_383_pp0_iter3_reg.read();
        icmp_ln27_reg_383_pp0_iter5_reg = icmp_ln27_reg_383_pp0_iter4_reg.read();
        icmp_ln27_reg_383_pp0_iter6_reg = icmp_ln27_reg_383_pp0_iter5_reg.read();
        icmp_ln27_reg_383_pp0_iter7_reg = icmp_ln27_reg_383_pp0_iter6_reg.read();
        icmp_ln27_reg_383_pp0_iter8_reg = icmp_ln27_reg_383_pp0_iter7_reg.read();
        j_0_reg_196_pp0_iter1_reg = j_0_reg_196.read();
        j_0_reg_196_pp0_iter2_reg = j_0_reg_196_pp0_iter1_reg.read();
        j_0_reg_196_pp0_iter3_reg = j_0_reg_196_pp0_iter2_reg.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()))) {
        j_reg_387 = j_fu_296_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter4_reg.read()))) {
        s_reg_452 = grp_fu_252_p1.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_imag_addr_reg_373 =  (sc_lv<8>) (zext_ln19_fu_284_p1.read());
        temp_real_addr_reg_368 =  (sc_lv<8>) (zext_ln19_fu_284_p1.read());
        w_reg_378 = grp_fu_252_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter5_reg.read()))) {
        tmp_10_reg_472 = grp_fu_245_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter6_reg.read()))) {
        tmp_11_reg_482 = grp_fu_239_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter7_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()))) {
        tmp_12_reg_493 = grp_fu_239_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter6_reg.read()))) {
        tmp_1_reg_477 = grp_fu_239_p2.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state12.read())) {
        tmp_2_reg_363 = grp_fu_259_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383.read()))) {
        tmp_3_reg_397 = grp_fu_249_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter1_reg.read()))) {
        tmp_4_reg_402 = grp_fu_245_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter5_reg.read()))) {
        tmp_5_reg_467 = grp_fu_245_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage2_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter7_reg.read()))) {
        tmp_8_reg_487 = grp_fu_239_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter4_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()))) {
        tmp_9_reg_457 = grp_fu_245_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter3_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()))) {
        tmp_i_i9_reg_417 = grp_sin_or_cos_double_s_fu_219_ap_return.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter3.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter3_reg.read()))) {
        tmp_i_i_reg_412 = grp_sin_or_cos_double_s_fu_219_ap_return.read();
    }
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state6.read())) {
        tmp_reg_358 = grp_fu_264_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter5_reg.read()))) {
        tmp_s_reg_462 = grp_fu_245_p2.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter1_reg.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4_11001.read(), ap_const_boolean_0))) {
        x_assign_reg_407 = grp_fu_255_p1.read();
    }
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) && esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln40_fu_327_p2.read()))) {
        zext_ln41_reg_507 = zext_ln41_fu_339_p1.read();
    }
}

void dft::thread_ap_CS_fsm_pp0_stage0() {
    ap_CS_fsm_pp0_stage0 = ap_CS_fsm.read()[14];
}

void dft::thread_ap_CS_fsm_pp0_stage1() {
    ap_CS_fsm_pp0_stage1 = ap_CS_fsm.read()[15];
}

void dft::thread_ap_CS_fsm_pp0_stage2() {
    ap_CS_fsm_pp0_stage2 = ap_CS_fsm.read()[16];
}

void dft::thread_ap_CS_fsm_pp0_stage3() {
    ap_CS_fsm_pp0_stage3 = ap_CS_fsm.read()[17];
}

void dft::thread_ap_CS_fsm_pp0_stage4() {
    ap_CS_fsm_pp0_stage4 = ap_CS_fsm.read()[18];
}

void dft::thread_ap_CS_fsm_state1() {
    ap_CS_fsm_state1 = ap_CS_fsm.read()[0];
}

void dft::thread_ap_CS_fsm_state12() {
    ap_CS_fsm_state12 = ap_CS_fsm.read()[11];
}

void dft::thread_ap_CS_fsm_state13() {
    ap_CS_fsm_state13 = ap_CS_fsm.read()[12];
}

void dft::thread_ap_CS_fsm_state14() {
    ap_CS_fsm_state14 = ap_CS_fsm.read()[13];
}

void dft::thread_ap_CS_fsm_state2() {
    ap_CS_fsm_state2 = ap_CS_fsm.read()[1];
}

void dft::thread_ap_CS_fsm_state57() {
    ap_CS_fsm_state57 = ap_CS_fsm.read()[19];
}

void dft::thread_ap_CS_fsm_state58() {
    ap_CS_fsm_state58 = ap_CS_fsm.read()[20];
}

void dft::thread_ap_CS_fsm_state59() {
    ap_CS_fsm_state59 = ap_CS_fsm.read()[21];
}

void dft::thread_ap_CS_fsm_state6() {
    ap_CS_fsm_state6 = ap_CS_fsm.read()[5];
}

void dft::thread_ap_CS_fsm_state7() {
    ap_CS_fsm_state7 = ap_CS_fsm.read()[6];
}

void dft::thread_ap_block_pp0_stage0() {
    ap_block_pp0_stage0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage0_00001() {
    ap_block_pp0_stage0_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage0_11001() {
    ap_block_pp0_stage0_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage0_subdone() {
    ap_block_pp0_stage0_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage1() {
    ap_block_pp0_stage1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage1_00001() {
    ap_block_pp0_stage1_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage1_11001() {
    ap_block_pp0_stage1_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage1_subdone() {
    ap_block_pp0_stage1_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage2() {
    ap_block_pp0_stage2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage2_00001() {
    ap_block_pp0_stage2_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage2_11001() {
    ap_block_pp0_stage2_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage2_subdone() {
    ap_block_pp0_stage2_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage3() {
    ap_block_pp0_stage3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage3_00001() {
    ap_block_pp0_stage3_00001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage3_11001() {
    ap_block_pp0_stage3_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage3_subdone() {
    ap_block_pp0_stage3_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage4() {
    ap_block_pp0_stage4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage4_11001() {
    ap_block_pp0_stage4_11001 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_pp0_stage4_subdone() {
    ap_block_pp0_stage4_subdone = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state15_pp0_stage0_iter0() {
    ap_block_state15_pp0_stage0_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state16_pp0_stage1_iter0() {
    ap_block_state16_pp0_stage1_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state17_pp0_stage2_iter0() {
    ap_block_state17_pp0_stage2_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state18_pp0_stage3_iter0() {
    ap_block_state18_pp0_stage3_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state19_pp0_stage4_iter0() {
    ap_block_state19_pp0_stage4_iter0 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state20_pp0_stage0_iter1() {
    ap_block_state20_pp0_stage0_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state21_pp0_stage1_iter1() {
    ap_block_state21_pp0_stage1_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state22_pp0_stage2_iter1() {
    ap_block_state22_pp0_stage2_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state23_pp0_stage3_iter1() {
    ap_block_state23_pp0_stage3_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state24_pp0_stage4_iter1() {
    ap_block_state24_pp0_stage4_iter1 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state25_pp0_stage0_iter2() {
    ap_block_state25_pp0_stage0_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state26_pp0_stage1_iter2() {
    ap_block_state26_pp0_stage1_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state27_pp0_stage2_iter2() {
    ap_block_state27_pp0_stage2_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state28_pp0_stage3_iter2() {
    ap_block_state28_pp0_stage3_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state29_pp0_stage4_iter2() {
    ap_block_state29_pp0_stage4_iter2 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state30_pp0_stage0_iter3() {
    ap_block_state30_pp0_stage0_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state31_pp0_stage1_iter3() {
    ap_block_state31_pp0_stage1_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state32_pp0_stage2_iter3() {
    ap_block_state32_pp0_stage2_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state33_pp0_stage3_iter3() {
    ap_block_state33_pp0_stage3_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state34_pp0_stage4_iter3() {
    ap_block_state34_pp0_stage4_iter3 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state35_pp0_stage0_iter4() {
    ap_block_state35_pp0_stage0_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state36_pp0_stage1_iter4() {
    ap_block_state36_pp0_stage1_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state37_pp0_stage2_iter4() {
    ap_block_state37_pp0_stage2_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state38_pp0_stage3_iter4() {
    ap_block_state38_pp0_stage3_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state39_pp0_stage4_iter4() {
    ap_block_state39_pp0_stage4_iter4 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state40_pp0_stage0_iter5() {
    ap_block_state40_pp0_stage0_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state41_pp0_stage1_iter5() {
    ap_block_state41_pp0_stage1_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state42_pp0_stage2_iter5() {
    ap_block_state42_pp0_stage2_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state43_pp0_stage3_iter5() {
    ap_block_state43_pp0_stage3_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state44_pp0_stage4_iter5() {
    ap_block_state44_pp0_stage4_iter5 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state45_pp0_stage0_iter6() {
    ap_block_state45_pp0_stage0_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state46_pp0_stage1_iter6() {
    ap_block_state46_pp0_stage1_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state47_pp0_stage2_iter6() {
    ap_block_state47_pp0_stage2_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state48_pp0_stage3_iter6() {
    ap_block_state48_pp0_stage3_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state49_pp0_stage4_iter6() {
    ap_block_state49_pp0_stage4_iter6 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state50_pp0_stage0_iter7() {
    ap_block_state50_pp0_stage0_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state51_pp0_stage1_iter7() {
    ap_block_state51_pp0_stage1_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state52_pp0_stage2_iter7() {
    ap_block_state52_pp0_stage2_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state53_pp0_stage3_iter7() {
    ap_block_state53_pp0_stage3_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state54_pp0_stage4_iter7() {
    ap_block_state54_pp0_stage4_iter7 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state55_pp0_stage0_iter8() {
    ap_block_state55_pp0_stage0_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_block_state56_pp0_stage1_iter8() {
    ap_block_state56_pp0_stage1_iter8 = !esl_seteq<1,1,1>(ap_const_boolean_1, ap_const_boolean_1);
}

void dft::thread_ap_condition_445() {
    ap_condition_445 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0));
}

void dft::thread_ap_condition_449() {
    ap_condition_449 = (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter2.read()));
}

void dft::thread_ap_condition_pp0_exit_iter0_state15() {
    if (esl_seteq<1,1,1>(icmp_ln27_fu_290_p2.read(), ap_const_lv1_1)) {
        ap_condition_pp0_exit_iter0_state15 = ap_const_logic_1;
    } else {
        ap_condition_pp0_exit_iter0_state15 = ap_const_logic_0;
    }
}

void dft::thread_ap_done() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) && 
         esl_seteq<1,1,1>(icmp_ln40_fu_327_p2.read(), ap_const_lv1_1))) {
        ap_done = ap_const_logic_1;
    } else {
        ap_done = ap_const_logic_0;
    }
}

void dft::thread_ap_enable_pp0() {
    ap_enable_pp0 = (ap_idle_pp0.read() ^ ap_const_logic_1);
}

void dft::thread_ap_idle() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_start.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()))) {
        ap_idle = ap_const_logic_1;
    } else {
        ap_idle = ap_const_logic_0;
    }
}

void dft::thread_ap_idle_pp0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter0.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter6.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_0, ap_enable_reg_pp0_iter8.read()))) {
        ap_idle_pp0 = ap_const_logic_1;
    } else {
        ap_idle_pp0 = ap_const_logic_0;
    }
}

void dft::thread_ap_phi_mux_empty_41_phi_fu_176_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter8_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        ap_phi_mux_empty_41_phi_fu_176_p4 = tmp_12_reg_493.read();
    } else {
        ap_phi_mux_empty_41_phi_fu_176_p4 = empty_41_reg_172.read();
    }
}

void dft::thread_ap_phi_mux_empty_42_phi_fu_188_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter7_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        ap_phi_mux_empty_42_phi_fu_188_p4 = tmp_8_reg_487.read();
    } else {
        ap_phi_mux_empty_42_phi_fu_188_p4 = empty_42_reg_184.read();
    }
}

void dft::thread_ap_phi_mux_j_0_phi_fu_200_p4() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        ap_phi_mux_j_0_phi_fu_200_p4 = j_reg_387.read();
    } else {
        ap_phi_mux_j_0_phi_fu_200_p4 = j_0_reg_196.read();
    }
}

void dft::thread_ap_ready() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) && 
         esl_seteq<1,1,1>(icmp_ln40_fu_327_p2.read(), ap_const_lv1_1))) {
        ap_ready = ap_const_logic_1;
    } else {
        ap_ready = ap_const_logic_0;
    }
}

void dft::thread_bitcast_ln30_1_fu_322_p1() {
    bitcast_ln30_1_fu_322_p1 = xor_ln30_fu_316_p2.read();
}

void dft::thread_bitcast_ln30_fu_313_p1() {
    bitcast_ln30_fu_313_p1 = tmp_i_i9_reg_417.read();
}

void dft::thread_grp_fu_239_opcode() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
         esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter5_reg.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage2_00001.read(), ap_const_boolean_0))) {
        grp_fu_239_opcode = ap_const_lv2_1;
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter5_reg.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0_00001.read(), ap_const_boolean_0)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter6_reg.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage3_00001.read(), ap_const_boolean_0)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
                 esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter7_reg.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage1_00001.read(), ap_const_boolean_0)))) {
        grp_fu_239_opcode = ap_const_lv2_0;
    } else {
        grp_fu_239_opcode = "XX";
    }
}

void dft::thread_grp_fu_239_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_239_p0 = ap_phi_mux_empty_41_phi_fu_176_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        grp_fu_239_p0 = ap_phi_mux_empty_42_phi_fu_188_p4.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_fu_239_p0 = tmp_5_reg_467.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        grp_fu_239_p0 = tmp_9_reg_457.read();
    } else {
        grp_fu_239_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_239_p1() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_239_p1 = tmp_11_reg_482.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        grp_fu_239_p1 = tmp_1_reg_477.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter6.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_fu_239_p1 = tmp_10_reg_472.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0))) {
        grp_fu_239_p1 = tmp_s_reg_462.read();
    } else {
        grp_fu_239_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_245_p0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0)))) {
        grp_fu_245_p0 = sample_imag_load_reg_447.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)))) {
        grp_fu_245_p0 = sample_real_load_reg_442.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
        grp_fu_245_p0 = tmp_3_reg_397.read();
    } else {
        grp_fu_245_p0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_245_p1() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0)) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0)))) {
        grp_fu_245_p1 = s_reg_452.read();
    } else if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage2.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage2.read(), ap_const_boolean_0)) || 
                (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                 esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter5.read()) && 
                 esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0)))) {
        grp_fu_245_p1 = c_reg_432.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage4.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage4.read(), ap_const_boolean_0))) {
        grp_fu_245_p1 = w_reg_378.read();
    } else {
        grp_fu_245_p1 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_249_p0() {
    grp_fu_249_p0 = esl_zext<32,9>(ap_phi_mux_j_0_phi_fu_200_p4.read());
}

void dft::thread_grp_fu_252_p0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        grp_fu_252_p0 = bitcast_ln30_1_fu_322_p1.read();
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        grp_fu_252_p0 = tmp_i_i_reg_412.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state13.read())) {
        grp_fu_252_p0 = tmp_2_reg_363.read();
    } else {
        grp_fu_252_p0 =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_grp_fu_264_p0() {
    grp_fu_264_p0 = esl_zext<32,9>(i_0_reg_160.read());
}

void dft::thread_grp_sin_or_cos_double_s_fu_219_ap_start() {
    grp_sin_or_cos_double_s_fu_219_ap_start = grp_sin_or_cos_double_s_fu_219_ap_start_reg.read();
}

void dft::thread_grp_sin_or_cos_double_s_fu_219_do_cos() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter1_reg.read())) {
        if (esl_seteq<1,1,1>(ap_condition_449.read(), ap_const_boolean_1)) {
            grp_sin_or_cos_double_s_fu_219_do_cos =  (sc_logic) (ap_const_lv1_0[0]);
        } else if (esl_seteq<1,1,1>(ap_condition_445.read(), ap_const_boolean_1)) {
            grp_sin_or_cos_double_s_fu_219_do_cos =  (sc_logic) (ap_const_lv1_1[0]);
        } else {
            grp_sin_or_cos_double_s_fu_219_do_cos = sc_logic('X');
        }
    } else {
        grp_sin_or_cos_double_s_fu_219_do_cos = sc_logic('X');
    }
}

void dft::thread_grp_sin_or_cos_double_s_fu_219_t_in() {
    if (esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter1_reg.read())) {
        if (esl_seteq<1,1,1>(ap_condition_449.read(), ap_const_boolean_1)) {
            grp_sin_or_cos_double_s_fu_219_t_in = x_assign_reg_407.read();
        } else if (esl_seteq<1,1,1>(ap_condition_445.read(), ap_const_boolean_1)) {
            grp_sin_or_cos_double_s_fu_219_t_in = grp_fu_255_p1.read();
        } else {
            grp_sin_or_cos_double_s_fu_219_t_in =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
        }
    } else {
        grp_sin_or_cos_double_s_fu_219_t_in =  (sc_lv<64>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_i_2_fu_273_p2() {
    i_2_fu_273_p2 = (!i_0_reg_160.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_0_reg_160.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void dft::thread_i_fu_333_p2() {
    i_fu_333_p2 = (!i_1_reg_208.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(i_1_reg_208.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void dft::thread_icmp_ln18_fu_267_p2() {
    icmp_ln18_fu_267_p2 = (!i_0_reg_160.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_0_reg_160.read() == ap_const_lv9_100);
}

void dft::thread_icmp_ln27_fu_290_p2() {
    icmp_ln27_fu_290_p2 = (!ap_phi_mux_j_0_phi_fu_200_p4.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(ap_phi_mux_j_0_phi_fu_200_p4.read() == ap_const_lv9_100);
}

void dft::thread_icmp_ln40_fu_327_p2() {
    icmp_ln40_fu_327_p2 = (!i_1_reg_208.read().is_01() || !ap_const_lv9_100.is_01())? sc_lv<1>(): sc_lv<1>(i_1_reg_208.read() == ap_const_lv9_100);
}

void dft::thread_j_fu_296_p2() {
    j_fu_296_p2 = (!ap_phi_mux_j_0_phi_fu_200_p4.read().is_01() || !ap_const_lv9_1.is_01())? sc_lv<9>(): (sc_biguint<9>(ap_phi_mux_j_0_phi_fu_200_p4.read()) + sc_biguint<9>(ap_const_lv9_1));
}

void dft::thread_sample_imag_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read())) {
        sample_imag_address0 =  (sc_lv<8>) (zext_ln41_reg_507.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        sample_imag_address0 =  (sc_lv<8>) (zext_ln34_fu_307_p1.read());
    } else {
        sample_imag_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dft::thread_sample_imag_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read()))) {
        sample_imag_ce0 = ap_const_logic_1;
    } else {
        sample_imag_ce0 = ap_const_logic_0;
    }
}

void dft::thread_sample_imag_d0() {
    sample_imag_d0 = temp_imag_q0.read();
}

void dft::thread_sample_imag_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read())) {
        sample_imag_we0 = ap_const_logic_1;
    } else {
        sample_imag_we0 = ap_const_logic_0;
    }
}

void dft::thread_sample_real_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read())) {
        sample_real_address0 =  (sc_lv<8>) (zext_ln41_reg_507.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage0.read(), ap_const_boolean_0))) {
        sample_real_address0 =  (sc_lv<8>) (zext_ln34_fu_307_p1.read());
    } else {
        sample_real_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dft::thread_sample_real_ce0() {
    if (((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage0.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage0_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter4.read())) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read()))) {
        sample_real_ce0 = ap_const_logic_1;
    } else {
        sample_real_ce0 = ap_const_logic_0;
    }
}

void dft::thread_sample_real_d0() {
    sample_real_d0 = temp_real_q0.read();
}

void dft::thread_sample_real_we0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state59.read())) {
        sample_real_we0 = ap_const_logic_1;
    } else {
        sample_real_we0 = ap_const_logic_0;
    }
}

void dft::thread_temp_imag_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read())) {
        temp_imag_address0 =  (sc_lv<8>) (zext_ln41_fu_339_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        temp_imag_address0 = temp_imag_addr_reg_373.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_imag_address0 =  (sc_lv<8>) (zext_ln19_fu_284_p1.read());
    } else {
        temp_imag_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dft::thread_temp_imag_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read())))) {
        temp_imag_ce0 = ap_const_logic_1;
    } else {
        temp_imag_ce0 = ap_const_logic_0;
    }
}

void dft::thread_temp_imag_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage1.read(), ap_const_boolean_0))) {
        temp_imag_d0 = tmp_12_reg_493.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_imag_d0 = ap_const_lv32_0;
    } else {
        temp_imag_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_temp_imag_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage1_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter8_reg.read())))) {
        temp_imag_we0 = ap_const_logic_1;
    } else {
        temp_imag_we0 = ap_const_logic_0;
    }
}

void dft::thread_temp_real_address0() {
    if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read())) {
        temp_real_address0 =  (sc_lv<8>) (zext_ln41_fu_339_p1.read());
    } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
                esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
                esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        temp_real_address0 = temp_real_addr_reg_368.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_real_address0 =  (sc_lv<8>) (zext_ln19_fu_284_p1.read());
    } else {
        temp_real_address0 =  (sc_lv<8>) ("XXXXXXXX");
    }
}

void dft::thread_temp_real_ce0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read())))) {
        temp_real_ce0 = ap_const_logic_1;
    } else {
        temp_real_ce0 = ap_const_logic_0;
    }
}

void dft::thread_temp_real_d0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
         esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
         esl_seteq<1,1,1>(ap_block_pp0_stage3.read(), ap_const_boolean_0))) {
        temp_real_d0 = tmp_8_reg_487.read();
    } else if (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read())) {
        temp_real_d0 = ap_const_lv32_0;
    } else {
        temp_real_d0 =  (sc_lv<32>) ("XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX");
    }
}

void dft::thread_temp_real_we0() {
    if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state14.read()) || 
         (esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage3.read()) && 
          esl_seteq<1,1,1>(ap_block_pp0_stage3_11001.read(), ap_const_boolean_0) && 
          esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter7.read()) && 
          esl_seteq<1,1,1>(ap_const_lv1_0, icmp_ln27_reg_383_pp0_iter7_reg.read())))) {
        temp_real_we0 = ap_const_logic_1;
    } else {
        temp_real_we0 = ap_const_logic_0;
    }
}

void dft::thread_xor_ln30_fu_316_p2() {
    xor_ln30_fu_316_p2 = (bitcast_ln30_fu_313_p1.read() ^ ap_const_lv64_8000000000000000);
}

void dft::thread_zext_ln19_fu_284_p1() {
    zext_ln19_fu_284_p1 = esl_zext<64,9>(i_0_reg_160.read());
}

void dft::thread_zext_ln34_fu_307_p1() {
    zext_ln34_fu_307_p1 = esl_zext<64,9>(j_0_reg_196_pp0_iter3_reg.read());
}

void dft::thread_zext_ln41_fu_339_p1() {
    zext_ln41_fu_339_p1 = esl_zext<64,9>(i_1_reg_208.read());
}

void dft::thread_ap_NS_fsm() {
    switch (ap_CS_fsm.read().to_uint64()) {
        case 1 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state1.read()) && esl_seteq<1,1,1>(ap_start.read(), ap_const_logic_1))) {
                ap_NS_fsm = ap_ST_fsm_state2;
            } else {
                ap_NS_fsm = ap_ST_fsm_state1;
            }
            break;
        case 2 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state2.read()) && esl_seteq<1,1,1>(icmp_ln18_fu_267_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state58;
            } else {
                ap_NS_fsm = ap_ST_fsm_state3;
            }
            break;
        case 4 : 
            ap_NS_fsm = ap_ST_fsm_state4;
            break;
        case 8 : 
            ap_NS_fsm = ap_ST_fsm_state5;
            break;
        case 16 : 
            ap_NS_fsm = ap_ST_fsm_state6;
            break;
        case 32 : 
            ap_NS_fsm = ap_ST_fsm_state7;
            break;
        case 64 : 
            ap_NS_fsm = ap_ST_fsm_state8;
            break;
        case 128 : 
            ap_NS_fsm = ap_ST_fsm_state9;
            break;
        case 256 : 
            ap_NS_fsm = ap_ST_fsm_state10;
            break;
        case 512 : 
            ap_NS_fsm = ap_ST_fsm_state11;
            break;
        case 1024 : 
            ap_NS_fsm = ap_ST_fsm_state12;
            break;
        case 2048 : 
            ap_NS_fsm = ap_ST_fsm_state13;
            break;
        case 4096 : 
            ap_NS_fsm = ap_ST_fsm_state14;
            break;
        case 8192 : 
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            break;
        case 16384 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln27_fu_290_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter0.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage0_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(icmp_ln27_fu_290_p2.read(), ap_const_lv1_1) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter1.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state57;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            }
            break;
        case 32768 : 
            if ((esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && !(esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter7.read(), ap_const_logic_0)))) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            } else if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_pp0_stage1.read()) && esl_seteq<1,1,1>(ap_const_logic_1, ap_enable_reg_pp0_iter8.read()) && esl_seteq<1,1,1>(ap_block_pp0_stage1_subdone.read(), ap_const_boolean_0) && esl_seteq<1,1,1>(ap_enable_reg_pp0_iter7.read(), ap_const_logic_0))) {
                ap_NS_fsm = ap_ST_fsm_state57;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage1;
            }
            break;
        case 65536 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage2_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage2;
            }
            break;
        case 131072 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage3_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage3;
            }
            break;
        case 262144 : 
            if (esl_seteq<1,1,1>(ap_block_pp0_stage4_subdone.read(), ap_const_boolean_0)) {
                ap_NS_fsm = ap_ST_fsm_pp0_stage0;
            } else {
                ap_NS_fsm = ap_ST_fsm_pp0_stage4;
            }
            break;
        case 524288 : 
            ap_NS_fsm = ap_ST_fsm_state2;
            break;
        case 1048576 : 
            if ((esl_seteq<1,1,1>(ap_const_logic_1, ap_CS_fsm_state58.read()) && esl_seteq<1,1,1>(icmp_ln40_fu_327_p2.read(), ap_const_lv1_1))) {
                ap_NS_fsm = ap_ST_fsm_state1;
            } else {
                ap_NS_fsm = ap_ST_fsm_state59;
            }
            break;
        case 2097152 : 
            ap_NS_fsm = ap_ST_fsm_state58;
            break;
        default : 
            ap_NS_fsm =  (sc_lv<22>) ("XXXXXXXXXXXXXXXXXXXXXX");
            break;
    }
}

void dft::thread_hdltv_gen() {
    const char* dump_tv = std::getenv("AP_WRITE_TV");
    if (!(dump_tv && string(dump_tv) == "on")) return;

    wait();

    mHdltvinHandle << "[ " << endl;
    mHdltvoutHandle << "[ " << endl;
    int ap_cycleNo = 0;
    while (1) {
        wait();
        const char* mComma = ap_cycleNo == 0 ? " " : ", " ;
        mHdltvinHandle << mComma << "{"  <<  " \"ap_rst\" :  \"" << ap_rst.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"ap_start\" :  \"" << ap_start.read() << "\" ";
        mHdltvoutHandle << mComma << "{"  <<  " \"ap_done\" :  \"" << ap_done.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_idle\" :  \"" << ap_idle.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"ap_ready\" :  \"" << ap_ready.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_address0\" :  \"" << sample_real_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_ce0\" :  \"" << sample_real_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_we0\" :  \"" << sample_real_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_real_d0\" :  \"" << sample_real_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sample_real_q0\" :  \"" << sample_real_q0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_address0\" :  \"" << sample_imag_address0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_ce0\" :  \"" << sample_imag_ce0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_we0\" :  \"" << sample_imag_we0.read() << "\" ";
        mHdltvoutHandle << " , " <<  " \"sample_imag_d0\" :  \"" << sample_imag_d0.read() << "\" ";
        mHdltvinHandle << " , " <<  " \"sample_imag_q0\" :  \"" << sample_imag_q0.read() << "\" ";
        mHdltvinHandle << "}" << std::endl;
        mHdltvoutHandle << "}" << std::endl;
        ap_cycleNo++;
    }
}

}

