// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

#ifndef _matrix_vector_HH_
#define _matrix_vector_HH_

#include "systemc.h"
#include "AESL_pkg.h"


namespace ap_rtl {

struct matrix_vector : public sc_module {
    // Port declarations 16
    sc_in_clk ap_clk;
    sc_in< sc_logic > ap_rst;
    sc_in< sc_logic > ap_start;
    sc_out< sc_logic > ap_done;
    sc_out< sc_logic > ap_idle;
    sc_out< sc_logic > ap_ready;
    sc_out< sc_lv<6> > M_address0;
    sc_out< sc_logic > M_ce0;
    sc_in< sc_lv<32> > M_q0;
    sc_out< sc_lv<3> > V_In_address0;
    sc_out< sc_logic > V_In_ce0;
    sc_in< sc_lv<32> > V_In_q0;
    sc_out< sc_lv<3> > V_Out_address0;
    sc_out< sc_logic > V_Out_ce0;
    sc_out< sc_logic > V_Out_we0;
    sc_out< sc_lv<32> > V_Out_d0;


    // Module declarations
    matrix_vector(sc_module_name name);
    SC_HAS_PROCESS(matrix_vector);

    ~matrix_vector();

    sc_trace_file* mVcdFile;

    ofstream mHdltvinHandle;
    ofstream mHdltvoutHandle;
    sc_signal< sc_lv<17> > ap_CS_fsm;
    sc_signal< sc_logic > ap_CS_fsm_state1;
    sc_signal< sc_lv<4> > add_ln10_fu_485_p2;
    sc_signal< sc_lv<4> > add_ln10_reg_750;
    sc_signal< sc_logic > ap_CS_fsm_state2;
    sc_signal< sc_lv<1> > icmp_ln10_fu_479_p2;
    sc_signal< sc_lv<32> > add_ln11_fu_497_p2;
    sc_signal< sc_logic > ap_CS_fsm_state3;
    sc_signal< sc_lv<4> > add_ln10_1_fu_509_p2;
    sc_signal< sc_lv<4> > add_ln10_1_reg_773;
    sc_signal< sc_logic > ap_CS_fsm_state4;
    sc_signal< sc_lv<1> > icmp_ln10_1_fu_503_p2;
    sc_signal< sc_lv<32> > add_ln11_1_fu_531_p2;
    sc_signal< sc_logic > ap_CS_fsm_state5;
    sc_signal< sc_lv<4> > add_ln10_2_fu_543_p2;
    sc_signal< sc_lv<4> > add_ln10_2_reg_796;
    sc_signal< sc_logic > ap_CS_fsm_state6;
    sc_signal< sc_lv<1> > icmp_ln10_2_fu_537_p2;
    sc_signal< sc_lv<32> > add_ln11_2_fu_563_p2;
    sc_signal< sc_logic > ap_CS_fsm_state7;
    sc_signal< sc_lv<4> > add_ln10_3_fu_575_p2;
    sc_signal< sc_lv<4> > add_ln10_3_reg_819;
    sc_signal< sc_logic > ap_CS_fsm_state8;
    sc_signal< sc_lv<1> > icmp_ln10_3_fu_569_p2;
    sc_signal< sc_lv<32> > add_ln11_3_fu_601_p2;
    sc_signal< sc_logic > ap_CS_fsm_state9;
    sc_signal< sc_lv<4> > add_ln10_4_fu_613_p2;
    sc_signal< sc_lv<4> > add_ln10_4_reg_842;
    sc_signal< sc_logic > ap_CS_fsm_state10;
    sc_signal< sc_lv<1> > icmp_ln10_4_fu_607_p2;
    sc_signal< sc_lv<32> > add_ln11_4_fu_633_p2;
    sc_signal< sc_logic > ap_CS_fsm_state11;
    sc_signal< sc_lv<4> > add_ln10_5_fu_645_p2;
    sc_signal< sc_lv<4> > add_ln10_5_reg_865;
    sc_signal< sc_logic > ap_CS_fsm_state12;
    sc_signal< sc_lv<1> > icmp_ln10_5_fu_639_p2;
    sc_signal< sc_lv<32> > add_ln11_5_fu_671_p2;
    sc_signal< sc_logic > ap_CS_fsm_state13;
    sc_signal< sc_lv<4> > add_ln10_6_fu_683_p2;
    sc_signal< sc_lv<4> > add_ln10_6_reg_888;
    sc_signal< sc_logic > ap_CS_fsm_state14;
    sc_signal< sc_lv<1> > icmp_ln10_6_fu_677_p2;
    sc_signal< sc_lv<32> > add_ln11_6_fu_703_p2;
    sc_signal< sc_logic > ap_CS_fsm_state15;
    sc_signal< sc_lv<4> > add_ln10_7_fu_715_p2;
    sc_signal< sc_lv<4> > add_ln10_7_reg_911;
    sc_signal< sc_logic > ap_CS_fsm_state16;
    sc_signal< sc_lv<1> > icmp_ln10_7_fu_709_p2;
    sc_signal< sc_lv<32> > add_ln11_7_fu_741_p2;
    sc_signal< sc_logic > ap_CS_fsm_state17;
    sc_signal< sc_lv<4> > j_0_0_reg_275;
    sc_signal< sc_lv<32> > sum_0_0_reg_286;
    sc_signal< sc_lv<4> > j_0_1_reg_299;
    sc_signal< sc_lv<32> > sum_0_1_reg_310;
    sc_signal< sc_lv<4> > j_0_2_reg_323;
    sc_signal< sc_lv<32> > sum_0_2_reg_334;
    sc_signal< sc_lv<4> > j_0_3_reg_347;
    sc_signal< sc_lv<32> > sum_0_3_reg_358;
    sc_signal< sc_lv<4> > j_0_4_reg_371;
    sc_signal< sc_lv<32> > sum_0_4_reg_382;
    sc_signal< sc_lv<4> > j_0_5_reg_395;
    sc_signal< sc_lv<32> > sum_0_5_reg_406;
    sc_signal< sc_lv<4> > j_0_6_reg_419;
    sc_signal< sc_lv<32> > sum_0_6_reg_430;
    sc_signal< sc_lv<4> > j_0_7_reg_443;
    sc_signal< sc_lv<32> > sum_0_7_reg_454;
    sc_signal< sc_lv<64> > zext_ln11_fu_491_p1;
    sc_signal< sc_lv<64> > zext_ln11_8_fu_526_p1;
    sc_signal< sc_lv<64> > zext_ln11_1_fu_515_p1;
    sc_signal< sc_lv<64> > tmp_8_fu_554_p3;
    sc_signal< sc_lv<64> > zext_ln11_2_fu_549_p1;
    sc_signal< sc_lv<64> > zext_ln11_9_fu_596_p1;
    sc_signal< sc_lv<64> > zext_ln11_3_fu_581_p1;
    sc_signal< sc_lv<64> > tmp_9_fu_624_p3;
    sc_signal< sc_lv<64> > zext_ln11_4_fu_619_p1;
    sc_signal< sc_lv<64> > zext_ln11_11_fu_666_p1;
    sc_signal< sc_lv<64> > zext_ln11_5_fu_651_p1;
    sc_signal< sc_lv<64> > tmp_s_fu_694_p3;
    sc_signal< sc_lv<64> > zext_ln11_6_fu_689_p1;
    sc_signal< sc_lv<64> > zext_ln11_12_fu_736_p1;
    sc_signal< sc_lv<64> > zext_ln11_7_fu_721_p1;
    sc_signal< sc_lv<32> > grp_fu_467_p0;
    sc_signal< sc_lv<32> > grp_fu_467_p1;
    sc_signal< sc_lv<32> > grp_fu_473_p0;
    sc_signal< sc_lv<32> > grp_fu_473_p1;
    sc_signal< sc_lv<32> > grp_fu_467_p2;
    sc_signal< sc_lv<4> > xor_ln11_fu_520_p2;
    sc_signal< sc_lv<32> > grp_fu_473_p2;
    sc_signal< sc_lv<4> > xor_ln11_1_fu_586_p2;
    sc_signal< sc_lv<5> > sext_ln11_fu_592_p1;
    sc_signal< sc_lv<6> > zext_ln11_10_fu_656_p1;
    sc_signal< sc_lv<6> > add_ln11_8_fu_660_p2;
    sc_signal< sc_lv<4> > xor_ln11_2_fu_726_p2;
    sc_signal< sc_lv<6> > sext_ln11_1_fu_732_p1;
    sc_signal< sc_lv<17> > ap_NS_fsm;
    static const sc_logic ap_const_logic_1;
    static const sc_logic ap_const_logic_0;
    static const sc_lv<17> ap_ST_fsm_state1;
    static const sc_lv<17> ap_ST_fsm_state2;
    static const sc_lv<17> ap_ST_fsm_state3;
    static const sc_lv<17> ap_ST_fsm_state4;
    static const sc_lv<17> ap_ST_fsm_state5;
    static const sc_lv<17> ap_ST_fsm_state6;
    static const sc_lv<17> ap_ST_fsm_state7;
    static const sc_lv<17> ap_ST_fsm_state8;
    static const sc_lv<17> ap_ST_fsm_state9;
    static const sc_lv<17> ap_ST_fsm_state10;
    static const sc_lv<17> ap_ST_fsm_state11;
    static const sc_lv<17> ap_ST_fsm_state12;
    static const sc_lv<17> ap_ST_fsm_state13;
    static const sc_lv<17> ap_ST_fsm_state14;
    static const sc_lv<17> ap_ST_fsm_state15;
    static const sc_lv<17> ap_ST_fsm_state16;
    static const sc_lv<17> ap_ST_fsm_state17;
    static const sc_lv<32> ap_const_lv32_0;
    static const sc_lv<32> ap_const_lv32_1;
    static const sc_lv<32> ap_const_lv32_2;
    static const sc_lv<32> ap_const_lv32_3;
    static const sc_lv<32> ap_const_lv32_4;
    static const sc_lv<32> ap_const_lv32_5;
    static const sc_lv<32> ap_const_lv32_6;
    static const sc_lv<32> ap_const_lv32_7;
    static const sc_lv<32> ap_const_lv32_8;
    static const sc_lv<32> ap_const_lv32_9;
    static const sc_lv<32> ap_const_lv32_A;
    static const sc_lv<32> ap_const_lv32_B;
    static const sc_lv<32> ap_const_lv32_C;
    static const sc_lv<32> ap_const_lv32_D;
    static const sc_lv<32> ap_const_lv32_E;
    static const sc_lv<32> ap_const_lv32_F;
    static const sc_lv<32> ap_const_lv32_10;
    static const sc_lv<4> ap_const_lv4_0;
    static const sc_lv<1> ap_const_lv1_1;
    static const sc_lv<64> ap_const_lv64_0;
    static const sc_lv<64> ap_const_lv64_1;
    static const sc_lv<64> ap_const_lv64_2;
    static const sc_lv<64> ap_const_lv64_3;
    static const sc_lv<64> ap_const_lv64_4;
    static const sc_lv<64> ap_const_lv64_5;
    static const sc_lv<64> ap_const_lv64_6;
    static const sc_lv<64> ap_const_lv64_7;
    static const sc_lv<4> ap_const_lv4_8;
    static const sc_lv<4> ap_const_lv4_1;
    static const sc_lv<60> ap_const_lv60_1;
    static const sc_lv<60> ap_const_lv60_2;
    static const sc_lv<6> ap_const_lv6_28;
    static const sc_lv<60> ap_const_lv60_3;
    static const bool ap_const_boolean_1;
    // Thread declarations
    void thread_ap_clk_no_reset_();
    void thread_M_address0();
    void thread_M_ce0();
    void thread_V_In_address0();
    void thread_V_In_ce0();
    void thread_V_Out_address0();
    void thread_V_Out_ce0();
    void thread_V_Out_d0();
    void thread_V_Out_we0();
    void thread_add_ln10_1_fu_509_p2();
    void thread_add_ln10_2_fu_543_p2();
    void thread_add_ln10_3_fu_575_p2();
    void thread_add_ln10_4_fu_613_p2();
    void thread_add_ln10_5_fu_645_p2();
    void thread_add_ln10_6_fu_683_p2();
    void thread_add_ln10_7_fu_715_p2();
    void thread_add_ln10_fu_485_p2();
    void thread_add_ln11_1_fu_531_p2();
    void thread_add_ln11_2_fu_563_p2();
    void thread_add_ln11_3_fu_601_p2();
    void thread_add_ln11_4_fu_633_p2();
    void thread_add_ln11_5_fu_671_p2();
    void thread_add_ln11_6_fu_703_p2();
    void thread_add_ln11_7_fu_741_p2();
    void thread_add_ln11_8_fu_660_p2();
    void thread_add_ln11_fu_497_p2();
    void thread_ap_CS_fsm_state1();
    void thread_ap_CS_fsm_state10();
    void thread_ap_CS_fsm_state11();
    void thread_ap_CS_fsm_state12();
    void thread_ap_CS_fsm_state13();
    void thread_ap_CS_fsm_state14();
    void thread_ap_CS_fsm_state15();
    void thread_ap_CS_fsm_state16();
    void thread_ap_CS_fsm_state17();
    void thread_ap_CS_fsm_state2();
    void thread_ap_CS_fsm_state3();
    void thread_ap_CS_fsm_state4();
    void thread_ap_CS_fsm_state5();
    void thread_ap_CS_fsm_state6();
    void thread_ap_CS_fsm_state7();
    void thread_ap_CS_fsm_state8();
    void thread_ap_CS_fsm_state9();
    void thread_ap_done();
    void thread_ap_idle();
    void thread_ap_ready();
    void thread_grp_fu_467_p0();
    void thread_grp_fu_467_p1();
    void thread_grp_fu_467_p2();
    void thread_grp_fu_473_p0();
    void thread_grp_fu_473_p1();
    void thread_grp_fu_473_p2();
    void thread_icmp_ln10_1_fu_503_p2();
    void thread_icmp_ln10_2_fu_537_p2();
    void thread_icmp_ln10_3_fu_569_p2();
    void thread_icmp_ln10_4_fu_607_p2();
    void thread_icmp_ln10_5_fu_639_p2();
    void thread_icmp_ln10_6_fu_677_p2();
    void thread_icmp_ln10_7_fu_709_p2();
    void thread_icmp_ln10_fu_479_p2();
    void thread_sext_ln11_1_fu_732_p1();
    void thread_sext_ln11_fu_592_p1();
    void thread_tmp_8_fu_554_p3();
    void thread_tmp_9_fu_624_p3();
    void thread_tmp_s_fu_694_p3();
    void thread_xor_ln11_1_fu_586_p2();
    void thread_xor_ln11_2_fu_726_p2();
    void thread_xor_ln11_fu_520_p2();
    void thread_zext_ln11_10_fu_656_p1();
    void thread_zext_ln11_11_fu_666_p1();
    void thread_zext_ln11_12_fu_736_p1();
    void thread_zext_ln11_1_fu_515_p1();
    void thread_zext_ln11_2_fu_549_p1();
    void thread_zext_ln11_3_fu_581_p1();
    void thread_zext_ln11_4_fu_619_p1();
    void thread_zext_ln11_5_fu_651_p1();
    void thread_zext_ln11_6_fu_689_p1();
    void thread_zext_ln11_7_fu_721_p1();
    void thread_zext_ln11_8_fu_526_p1();
    void thread_zext_ln11_9_fu_596_p1();
    void thread_zext_ln11_fu_491_p1();
    void thread_ap_NS_fsm();
    void thread_hdltv_gen();
};

}

using namespace ap_rtl;

#endif
