// ==============================================================
// RTL generated by Vivado(TM) HLS - High-Level Synthesis from C, C++ and OpenCL
// Version: 2020.1
// Copyright (C) 1986-2020 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module fft_stage81 (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_continue,
        ap_idle,
        ap_ready,
        X_R_V_address0,
        X_R_V_ce0,
        X_R_V_q0,
        X_R_V_address1,
        X_R_V_ce1,
        X_R_V_q1,
        X_I_V_address0,
        X_I_V_ce0,
        X_I_V_q0,
        X_I_V_address1,
        X_I_V_ce1,
        X_I_V_q1,
        Out_R_V_address0,
        Out_R_V_ce0,
        Out_R_V_we0,
        Out_R_V_d0,
        Out_R_V_address1,
        Out_R_V_ce1,
        Out_R_V_we1,
        Out_R_V_d1,
        Out_I_V_address0,
        Out_I_V_ce0,
        Out_I_V_we0,
        Out_I_V_d0,
        Out_I_V_address1,
        Out_I_V_ce1,
        Out_I_V_we1,
        Out_I_V_d1
);

parameter    ap_ST_fsm_state1 = 7'd1;
parameter    ap_ST_fsm_state2 = 7'd2;
parameter    ap_ST_fsm_state3 = 7'd4;
parameter    ap_ST_fsm_state4 = 7'd8;
parameter    ap_ST_fsm_state5 = 7'd16;
parameter    ap_ST_fsm_state6 = 7'd32;
parameter    ap_ST_fsm_state7 = 7'd64;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
input   ap_continue;
output   ap_idle;
output   ap_ready;
output  [9:0] X_R_V_address0;
output   X_R_V_ce0;
input  [21:0] X_R_V_q0;
output  [9:0] X_R_V_address1;
output   X_R_V_ce1;
input  [21:0] X_R_V_q1;
output  [9:0] X_I_V_address0;
output   X_I_V_ce0;
input  [21:0] X_I_V_q0;
output  [9:0] X_I_V_address1;
output   X_I_V_ce1;
input  [21:0] X_I_V_q1;
output  [9:0] Out_R_V_address0;
output   Out_R_V_ce0;
output   Out_R_V_we0;
output  [21:0] Out_R_V_d0;
output  [9:0] Out_R_V_address1;
output   Out_R_V_ce1;
output   Out_R_V_we1;
output  [21:0] Out_R_V_d1;
output  [9:0] Out_I_V_address0;
output   Out_I_V_ce0;
output   Out_I_V_we0;
output  [21:0] Out_I_V_d0;
output  [9:0] Out_I_V_address1;
output   Out_I_V_ce1;
output   Out_I_V_we1;
output  [21:0] Out_I_V_d1;

reg ap_done;
reg ap_idle;
reg ap_ready;
reg X_R_V_ce0;
reg X_R_V_ce1;
reg X_I_V_ce0;
reg X_I_V_ce1;
reg Out_R_V_ce0;
reg Out_R_V_we0;
reg Out_R_V_ce1;
reg Out_R_V_we1;
reg Out_I_V_ce0;
reg Out_I_V_we0;
reg Out_I_V_ce1;
reg Out_I_V_we1;

reg    ap_done_reg;
(* fsm_encoding = "none" *) reg   [6:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [31:0] zext_ln891_fu_313_p1;
reg   [31:0] zext_ln891_reg_1313;
wire    ap_CS_fsm_state2;
wire   [63:0] select_ln885_fu_605_p3;
reg   [63:0] select_ln885_reg_1318;
wire   [0:0] ap_phi_mux_i_phi_fu_258_p4;
wire   [13:0] a_V_fu_613_p2;
reg   [13:0] a_V_reg_1324;
wire   [63:0] grp_sin_or_cos_double_s_fu_275_ap_return;
reg   [63:0] v_assign_reg_1329;
wire    ap_CS_fsm_state4;
wire    grp_sin_or_cos_double_s_fu_275_ap_ready;
wire    grp_sin_or_cos_double_s_fu_275_ap_done;
wire    grp_sin_or_cos_double_s_fu_294_ap_ready;
wire    grp_sin_or_cos_double_s_fu_294_ap_done;
reg    ap_block_state4_on_subcall_done;
wire   [63:0] grp_sin_or_cos_double_s_fu_294_ap_return;
reg   [63:0] v_assign_s_reg_1334;
wire  signed [32:0] sext_ln1118_fu_1177_p1;
reg  signed [32:0] sext_ln1118_reg_1339;
wire    ap_CS_fsm_state5;
wire  signed [32:0] sext_ln1118_28_fu_1181_p1;
reg  signed [32:0] sext_ln1118_28_reg_1345;
wire  signed [63:0] sext_ln55_fu_1207_p1;
reg  signed [63:0] sext_ln55_reg_1354;
wire    ap_CS_fsm_state6;
wire   [0:0] icmp_ln53_fu_1195_p2;
wire  signed [63:0] sext_ln57_fu_1213_p1;
reg  signed [63:0] sext_ln57_reg_1370;
wire   [31:0] i_12_fu_1219_p2;
reg   [31:0] i_12_reg_1386;
wire    grp_sin_or_cos_double_s_fu_275_ap_start;
wire    grp_sin_or_cos_double_s_fu_275_ap_idle;
wire    grp_sin_or_cos_double_s_fu_275_do_cos;
wire    grp_sin_or_cos_double_s_fu_294_ap_start;
wire    grp_sin_or_cos_double_s_fu_294_ap_idle;
wire    grp_sin_or_cos_double_s_fu_294_do_cos;
reg  signed [13:0] tmp_V_reg_242;
reg    ap_block_state1;
reg   [0:0] i_reg_253;
reg  signed [31:0] i_0_reg_266;
wire    ap_CS_fsm_state7;
reg    grp_sin_or_cos_double_s_fu_275_ap_start_reg;
wire    ap_CS_fsm_state3;
reg    grp_sin_or_cos_double_s_fu_294_ap_start_reg;
wire  signed [21:0] sext_ln891_fu_323_p1;
reg   [21:0] p_Result_s_fu_327_p4;
wire   [31:0] p_Result_159_fu_337_p3;
reg   [31:0] l_fu_345_p3;
wire   [31:0] sub_ln894_fu_353_p2;
wire   [31:0] lsb_index_fu_363_p2;
wire   [30:0] tmp_fu_369_p4;
wire   [4:0] trunc_ln897_fu_385_p1;
wire   [4:0] sub_ln897_fu_389_p2;
wire   [21:0] zext_ln897_fu_395_p1;
wire   [21:0] lshr_ln897_fu_399_p2;
wire   [21:0] p_Result_152_fu_405_p2;
wire   [0:0] icmp_ln897_fu_379_p2;
wire   [0:0] icmp_ln897_1_fu_411_p2;
wire   [0:0] tmp_74_fu_423_p3;
wire   [21:0] trunc_ln894_fu_359_p1;
wire   [21:0] add_ln899_fu_437_p2;
wire   [0:0] p_Result_153_fu_443_p3;
wire   [0:0] xor_ln899_fu_431_p2;
wire   [0:0] and_ln899_fu_451_p2;
wire   [0:0] a_fu_417_p2;
wire   [0:0] or_ln899_fu_457_p2;
wire   [31:0] zext_ln907_10_fu_475_p1;
wire   [31:0] add_ln908_fu_485_p2;
wire   [31:0] lshr_ln908_fu_491_p2;
wire   [31:0] sub_ln908_fu_501_p2;
wire   [63:0] m_fu_471_p1;
wire   [63:0] zext_ln908_1_fu_507_p1;
wire   [0:0] icmp_ln908_fu_479_p2;
wire   [63:0] zext_ln908_fu_497_p1;
wire   [63:0] shl_ln908_fu_511_p2;
wire   [31:0] or_ln_fu_463_p3;
wire   [63:0] zext_ln911_fu_525_p1;
wire   [63:0] m_47_fu_517_p3;
wire   [63:0] m_48_fu_529_p2;
wire   [62:0] m_s_fu_535_p4;
wire   [0:0] tmp_75_fu_549_p3;
wire   [10:0] trunc_ln893_fu_565_p1;
wire   [10:0] sub_ln915_fu_569_p2;
wire   [10:0] select_ln915_fu_557_p3;
wire   [10:0] add_ln915_fu_575_p2;
wire   [63:0] m_51_fu_545_p1;
wire   [11:0] tmp_4_fu_581_p3;
wire   [63:0] p_Result_160_fu_589_p5;
wire   [0:0] icmp_ln885_fu_317_p2;
wire   [63:0] bitcast_ln729_fu_601_p1;
wire   [63:0] ireg_V_fu_619_p1;
wire   [10:0] exp_tmp_V_fu_634_p4;
wire   [51:0] trunc_ln565_fu_648_p1;
wire   [52:0] tmp_5_fu_652_p3;
wire   [53:0] p_Result_162_fu_660_p1;
wire   [0:0] p_Result_161_fu_626_p3;
wire   [53:0] man_V_46_fu_664_p2;
wire   [62:0] trunc_ln556_fu_622_p1;
wire   [11:0] zext_ln461_1_fu_644_p1;
wire   [11:0] F2_fu_684_p2;
wire   [0:0] icmp_ln581_1_fu_690_p2;
wire   [11:0] add_ln581_1_fu_696_p2;
wire   [11:0] sub_ln581_1_fu_702_p2;
wire  signed [11:0] sh_amt_fu_708_p3;
wire   [53:0] man_V_47_fu_670_p3;
wire  signed [31:0] sext_ln581_fu_716_p1;
wire   [53:0] zext_ln586_1_fu_746_p1;
wire   [53:0] ashr_ln586_1_fu_750_p2;
wire   [0:0] tmp_77_fu_760_p3;
wire   [21:0] trunc_ln583_fu_730_p1;
wire  signed [21:0] sext_ln581_28_fu_720_p1;
wire   [0:0] icmp_ln571_1_fu_678_p2;
wire   [0:0] icmp_ln582_1_fu_724_p2;
wire   [0:0] xor_ln571_fu_782_p2;
wire   [0:0] or_ln582_fu_794_p2;
wire   [0:0] xor_ln582_fu_800_p2;
wire   [0:0] icmp_ln585_1_fu_734_p2;
wire   [0:0] and_ln581_fu_806_p2;
wire   [0:0] xor_ln585_fu_812_p2;
wire   [0:0] or_ln581_fu_830_p2;
wire   [0:0] icmp_ln603_1_fu_740_p2;
wire   [0:0] xor_ln581_fu_836_p2;
wire   [0:0] and_ln603_fu_842_p2;
wire   [21:0] shl_ln604_1_fu_776_p2;
wire   [21:0] trunc_ln586_fu_756_p1;
wire   [0:0] and_ln585_28_fu_824_p2;
wire   [0:0] and_ln585_fu_818_p2;
wire   [21:0] select_ln588_fu_768_p3;
wire   [0:0] and_ln582_fu_788_p2;
wire   [0:0] or_ln603_fu_856_p2;
wire   [21:0] select_ln603_fu_848_p3;
wire   [21:0] select_ln603_64_fu_862_p3;
wire   [0:0] or_ln603_46_fu_870_p2;
wire   [0:0] or_ln603_47_fu_884_p2;
wire   [21:0] select_ln603_65_fu_876_p3;
wire   [63:0] ireg_V_10_fu_898_p1;
wire   [10:0] exp_tmp_V_10_fu_913_p4;
wire   [51:0] trunc_ln565_10_fu_927_p1;
wire   [52:0] tmp_6_fu_931_p3;
wire   [53:0] p_Result_164_fu_939_p1;
wire   [0:0] p_Result_163_fu_905_p3;
wire   [53:0] man_V_49_fu_943_p2;
wire   [62:0] trunc_ln556_10_fu_901_p1;
wire   [11:0] zext_ln461_fu_923_p1;
wire   [11:0] F2_10_fu_963_p2;
wire   [0:0] icmp_ln581_fu_969_p2;
wire   [11:0] add_ln581_fu_975_p2;
wire   [11:0] sub_ln581_fu_981_p2;
wire  signed [11:0] sh_amt_10_fu_987_p3;
wire   [53:0] man_V_50_fu_949_p3;
wire  signed [31:0] sext_ln581_29_fu_995_p1;
wire   [53:0] zext_ln586_fu_1025_p1;
wire   [53:0] ashr_ln586_fu_1029_p2;
wire   [0:0] tmp_79_fu_1039_p3;
wire   [21:0] trunc_ln583_10_fu_1009_p1;
wire  signed [21:0] sext_ln581_30_fu_999_p1;
wire   [0:0] icmp_ln571_fu_957_p2;
wire   [0:0] icmp_ln582_fu_1003_p2;
wire   [0:0] xor_ln571_10_fu_1061_p2;
wire   [0:0] or_ln582_10_fu_1073_p2;
wire   [0:0] xor_ln582_10_fu_1079_p2;
wire   [0:0] icmp_ln585_fu_1013_p2;
wire   [0:0] and_ln581_10_fu_1085_p2;
wire   [0:0] xor_ln585_10_fu_1091_p2;
wire   [0:0] or_ln581_10_fu_1109_p2;
wire   [0:0] icmp_ln603_fu_1019_p2;
wire   [0:0] xor_ln581_10_fu_1115_p2;
wire   [0:0] and_ln603_10_fu_1121_p2;
wire   [21:0] shl_ln604_fu_1055_p2;
wire   [21:0] trunc_ln586_10_fu_1035_p1;
wire   [0:0] and_ln585_30_fu_1103_p2;
wire   [0:0] and_ln585_29_fu_1097_p2;
wire   [21:0] select_ln588_10_fu_1047_p3;
wire   [0:0] and_ln582_10_fu_1067_p2;
wire   [0:0] or_ln603_48_fu_1135_p2;
wire   [21:0] select_ln603_67_fu_1127_p3;
wire   [21:0] select_ln603_68_fu_1141_p3;
wire   [0:0] or_ln603_49_fu_1149_p2;
wire   [0:0] or_ln603_50_fu_1163_p2;
wire   [21:0] select_ln603_69_fu_1155_p3;
wire   [21:0] c_V_fu_890_p3;
wire   [21:0] s_V_fu_1169_p3;
wire   [21:0] tmp_80_fu_1185_p4;
wire   [31:0] i_lower_fu_1201_p2;
wire  signed [21:0] mul_ln700_fu_1233_p0;
wire  signed [21:0] mul_ln700_fu_1233_p1;
wire  signed [32:0] sext_ln1118_29_fu_1225_p1;
wire  signed [21:0] mul_ln1193_fu_1238_p0;
wire  signed [21:0] mul_ln1193_fu_1238_p1;
wire  signed [32:0] sext_ln1118_30_fu_1229_p1;
wire   [32:0] mul_ln700_fu_1233_p2;
wire   [32:0] mul_ln1193_fu_1238_p2;
wire   [32:0] ret_V_fu_1243_p2;
wire  signed [21:0] mul_ln700_10_fu_1259_p0;
wire  signed [21:0] mul_ln700_10_fu_1259_p1;
wire  signed [21:0] mul_ln1192_fu_1264_p0;
wire  signed [21:0] mul_ln1192_fu_1264_p1;
wire   [32:0] mul_ln1192_fu_1264_p2;
wire   [32:0] mul_ln700_10_fu_1259_p2;
wire   [32:0] ret_V_22_fu_1269_p2;
wire   [21:0] temp_R_V_fu_1249_p4;
wire   [21:0] temp_I_V_fu_1275_p4;
reg   [6:0] ap_NS_fsm;

// power-on initialization
initial begin
#0 ap_done_reg = 1'b0;
#0 ap_CS_fsm = 7'd1;
#0 grp_sin_or_cos_double_s_fu_275_ap_start_reg = 1'b0;
#0 grp_sin_or_cos_double_s_fu_294_ap_start_reg = 1'b0;
end

sin_or_cos_double_s grp_sin_or_cos_double_s_fu_275(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_s_fu_275_ap_start),
    .ap_done(grp_sin_or_cos_double_s_fu_275_ap_done),
    .ap_idle(grp_sin_or_cos_double_s_fu_275_ap_idle),
    .ap_ready(grp_sin_or_cos_double_s_fu_275_ap_ready),
    .t_in(select_ln885_reg_1318),
    .do_cos(grp_sin_or_cos_double_s_fu_275_do_cos),
    .ap_return(grp_sin_or_cos_double_s_fu_275_ap_return)
);

sin_or_cos_double_s grp_sin_or_cos_double_s_fu_294(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(grp_sin_or_cos_double_s_fu_294_ap_start),
    .ap_done(grp_sin_or_cos_double_s_fu_294_ap_done),
    .ap_idle(grp_sin_or_cos_double_s_fu_294_ap_idle),
    .ap_ready(grp_sin_or_cos_double_s_fu_294_ap_ready),
    .t_in(select_ln885_reg_1318),
    .do_cos(grp_sin_or_cos_double_s_fu_294_do_cos),
    .ap_return(grp_sin_or_cos_double_s_fu_294_ap_return)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_phi_mux_i_phi_fu_258_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_s_fu_275_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_sin_or_cos_double_s_fu_275_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_s_fu_275_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_s_fu_275_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        grp_sin_or_cos_double_s_fu_294_ap_start_reg <= 1'b0;
    end else begin
        if ((1'b1 == ap_CS_fsm_state3)) begin
            grp_sin_or_cos_double_s_fu_294_ap_start_reg <= 1'b1;
        end else if ((grp_sin_or_cos_double_s_fu_294_ap_ready == 1'b1)) begin
            grp_sin_or_cos_double_s_fu_294_ap_start_reg <= 1'b0;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        i_0_reg_266 <= i_12_reg_1386;
    end else if ((1'b1 == ap_CS_fsm_state5)) begin
        i_0_reg_266 <= zext_ln891_reg_1313;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_1195_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        i_reg_253 <= 1'd1;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        i_reg_253 <= 1'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln53_fu_1195_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
        tmp_V_reg_242 <= a_V_reg_1324;
    end else if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
        tmp_V_reg_242 <= 14'd0;
    end
end

always @ (posedge ap_clk) begin
    if (((ap_phi_mux_i_phi_fu_258_p4 == 1'd0) & (1'b1 == ap_CS_fsm_state2))) begin
        a_V_reg_1324 <= a_V_fu_613_p2;
        select_ln885_reg_1318 <= select_ln885_fu_605_p3;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b1 == ap_CS_fsm_state6) & (icmp_ln53_fu_1195_p2 == 1'd1))) begin
        i_12_reg_1386 <= i_12_fu_1219_p2;
        sext_ln55_reg_1354 <= sext_ln55_fu_1207_p1;
        sext_ln57_reg_1370 <= sext_ln57_fu_1213_p1;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state5)) begin
        sext_ln1118_28_reg_1345 <= sext_ln1118_28_fu_1181_p1;
        sext_ln1118_reg_1339 <= sext_ln1118_fu_1177_p1;
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
        v_assign_reg_1329 <= grp_sin_or_cos_double_s_fu_275_ap_return;
        v_assign_s_reg_1334 <= grp_sin_or_cos_double_s_fu_294_ap_return;
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_CS_fsm_state2)) begin
        zext_ln891_reg_1313[0] <= zext_ln891_fu_313_p1[0];
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_I_V_ce0 = 1'b1;
    end else begin
        Out_I_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_I_V_ce1 = 1'b1;
    end else begin
        Out_I_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_I_V_we0 = 1'b1;
    end else begin
        Out_I_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_I_V_we1 = 1'b1;
    end else begin
        Out_I_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_R_V_ce0 = 1'b1;
    end else begin
        Out_R_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_R_V_ce1 = 1'b1;
    end else begin
        Out_R_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_R_V_we0 = 1'b1;
    end else begin
        Out_R_V_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state7)) begin
        Out_R_V_we1 = 1'b1;
    end else begin
        Out_R_V_we1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        X_I_V_ce0 = 1'b1;
    end else begin
        X_I_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        X_I_V_ce1 = 1'b1;
    end else begin
        X_I_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        X_R_V_ce0 = 1'b1;
    end else begin
        X_R_V_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((1'b1 == ap_CS_fsm_state6)) begin
        X_R_V_ce1 = 1'b1;
    end else begin
        X_R_V_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_i_phi_fu_258_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_done = 1'b1;
    end else begin
        ap_done = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_phi_mux_i_phi_fu_258_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
        ap_ready = 1'b1;
    end else begin
        ap_ready = 1'b0;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            if ((~((ap_start == 1'b0) | (ap_done_reg == 1'b1)) & (1'b1 == ap_CS_fsm_state1))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end
        end
        ap_ST_fsm_state2 : begin
            if (((ap_phi_mux_i_phi_fu_258_p4 == 1'd1) & (1'b1 == ap_CS_fsm_state2))) begin
                ap_NS_fsm = ap_ST_fsm_state1;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state3;
            end
        end
        ap_ST_fsm_state3 : begin
            ap_NS_fsm = ap_ST_fsm_state4;
        end
        ap_ST_fsm_state4 : begin
            if (((1'b0 == ap_block_state4_on_subcall_done) & (1'b1 == ap_CS_fsm_state4))) begin
                ap_NS_fsm = ap_ST_fsm_state5;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state4;
            end
        end
        ap_ST_fsm_state5 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        ap_ST_fsm_state6 : begin
            if (((icmp_ln53_fu_1195_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state6))) begin
                ap_NS_fsm = ap_ST_fsm_state2;
            end else begin
                ap_NS_fsm = ap_ST_fsm_state7;
            end
        end
        ap_ST_fsm_state7 : begin
            ap_NS_fsm = ap_ST_fsm_state6;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign F2_10_fu_963_p2 = (12'd1075 - zext_ln461_fu_923_p1);

assign F2_fu_684_p2 = (12'd1075 - zext_ln461_1_fu_644_p1);

assign Out_I_V_address0 = sext_ln55_reg_1354;

assign Out_I_V_address1 = sext_ln57_reg_1370;

assign Out_I_V_d0 = (X_I_V_q1 - temp_I_V_fu_1275_p4);

assign Out_I_V_d1 = (X_I_V_q1 + temp_I_V_fu_1275_p4);

assign Out_R_V_address0 = sext_ln55_reg_1354;

assign Out_R_V_address1 = sext_ln57_reg_1370;

assign Out_R_V_d0 = (X_R_V_q1 - temp_R_V_fu_1249_p4);

assign Out_R_V_d1 = (X_R_V_q1 + temp_R_V_fu_1249_p4);

assign X_I_V_address0 = sext_ln55_fu_1207_p1;

assign X_I_V_address1 = sext_ln57_fu_1213_p1;

assign X_R_V_address0 = sext_ln55_fu_1207_p1;

assign X_R_V_address1 = sext_ln57_fu_1213_p1;

assign a_V_fu_613_p2 = ($signed(14'd9950) + $signed(tmp_V_reg_242));

assign a_fu_417_p2 = (icmp_ln897_fu_379_p2 & icmp_ln897_1_fu_411_p2);

assign add_ln581_1_fu_696_p2 = ($signed(12'd4085) + $signed(F2_fu_684_p2));

assign add_ln581_fu_975_p2 = ($signed(12'd4085) + $signed(F2_10_fu_963_p2));

assign add_ln899_fu_437_p2 = ($signed(22'd4194251) + $signed(trunc_ln894_fu_359_p1));

assign add_ln908_fu_485_p2 = ($signed(32'd4294967242) + $signed(sub_ln894_fu_353_p2));

assign add_ln915_fu_575_p2 = (sub_ln915_fu_569_p2 + select_ln915_fu_557_p3);

assign and_ln581_10_fu_1085_p2 = (xor_ln582_10_fu_1079_p2 & icmp_ln581_fu_969_p2);

assign and_ln581_fu_806_p2 = (xor_ln582_fu_800_p2 & icmp_ln581_1_fu_690_p2);

assign and_ln582_10_fu_1067_p2 = (xor_ln571_10_fu_1061_p2 & icmp_ln582_fu_1003_p2);

assign and_ln582_fu_788_p2 = (xor_ln571_fu_782_p2 & icmp_ln582_1_fu_724_p2);

assign and_ln585_28_fu_824_p2 = (icmp_ln585_1_fu_734_p2 & and_ln581_fu_806_p2);

assign and_ln585_29_fu_1097_p2 = (xor_ln585_10_fu_1091_p2 & and_ln581_10_fu_1085_p2);

assign and_ln585_30_fu_1103_p2 = (icmp_ln585_fu_1013_p2 & and_ln581_10_fu_1085_p2);

assign and_ln585_fu_818_p2 = (xor_ln585_fu_812_p2 & and_ln581_fu_806_p2);

assign and_ln603_10_fu_1121_p2 = (xor_ln581_10_fu_1115_p2 & icmp_ln603_fu_1019_p2);

assign and_ln603_fu_842_p2 = (xor_ln581_fu_836_p2 & icmp_ln603_1_fu_740_p2);

assign and_ln899_fu_451_p2 = (xor_ln899_fu_431_p2 & p_Result_153_fu_443_p3);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

assign ap_CS_fsm_state2 = ap_CS_fsm[32'd1];

assign ap_CS_fsm_state3 = ap_CS_fsm[32'd2];

assign ap_CS_fsm_state4 = ap_CS_fsm[32'd3];

assign ap_CS_fsm_state5 = ap_CS_fsm[32'd4];

assign ap_CS_fsm_state6 = ap_CS_fsm[32'd5];

assign ap_CS_fsm_state7 = ap_CS_fsm[32'd6];

always @ (*) begin
    ap_block_state1 = ((ap_start == 1'b0) | (ap_done_reg == 1'b1));
end

always @ (*) begin
    ap_block_state4_on_subcall_done = ((grp_sin_or_cos_double_s_fu_294_ap_done == 1'b0) | (grp_sin_or_cos_double_s_fu_275_ap_done == 1'b0));
end

assign ap_phi_mux_i_phi_fu_258_p4 = i_reg_253;

assign ashr_ln586_1_fu_750_p2 = $signed(man_V_47_fu_670_p3) >>> zext_ln586_1_fu_746_p1;

assign ashr_ln586_fu_1029_p2 = $signed(man_V_50_fu_949_p3) >>> zext_ln586_fu_1025_p1;

assign bitcast_ln729_fu_601_p1 = p_Result_160_fu_589_p5;

assign c_V_fu_890_p3 = ((or_ln603_47_fu_884_p2[0:0] === 1'b1) ? select_ln603_65_fu_876_p3 : 22'd0);

assign exp_tmp_V_10_fu_913_p4 = {{ireg_V_10_fu_898_p1[62:52]}};

assign exp_tmp_V_fu_634_p4 = {{ireg_V_fu_619_p1[62:52]}};

assign grp_sin_or_cos_double_s_fu_275_ap_start = grp_sin_or_cos_double_s_fu_275_ap_start_reg;

assign grp_sin_or_cos_double_s_fu_275_do_cos = 1'd1;

assign grp_sin_or_cos_double_s_fu_294_ap_start = grp_sin_or_cos_double_s_fu_294_ap_start_reg;

assign grp_sin_or_cos_double_s_fu_294_do_cos = 1'd0;

assign i_12_fu_1219_p2 = ($signed(i_0_reg_266) + $signed(32'd2));

assign i_lower_fu_1201_p2 = ($signed(i_0_reg_266) + $signed(32'd1));

assign icmp_ln53_fu_1195_p2 = (($signed(tmp_80_fu_1185_p4) < $signed(22'd1)) ? 1'b1 : 1'b0);

assign icmp_ln571_1_fu_678_p2 = ((trunc_ln556_fu_622_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln571_fu_957_p2 = ((trunc_ln556_10_fu_901_p1 == 63'd0) ? 1'b1 : 1'b0);

assign icmp_ln581_1_fu_690_p2 = (($signed(F2_fu_684_p2) > $signed(12'd11)) ? 1'b1 : 1'b0);

assign icmp_ln581_fu_969_p2 = (($signed(F2_10_fu_963_p2) > $signed(12'd11)) ? 1'b1 : 1'b0);

assign icmp_ln582_1_fu_724_p2 = ((F2_fu_684_p2 == 12'd11) ? 1'b1 : 1'b0);

assign icmp_ln582_fu_1003_p2 = ((F2_10_fu_963_p2 == 12'd11) ? 1'b1 : 1'b0);

assign icmp_ln585_1_fu_734_p2 = ((sh_amt_fu_708_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln585_fu_1013_p2 = ((sh_amt_10_fu_987_p3 < 12'd54) ? 1'b1 : 1'b0);

assign icmp_ln603_1_fu_740_p2 = ((sh_amt_fu_708_p3 < 12'd22) ? 1'b1 : 1'b0);

assign icmp_ln603_fu_1019_p2 = ((sh_amt_10_fu_987_p3 < 12'd22) ? 1'b1 : 1'b0);

assign icmp_ln885_fu_317_p2 = ((tmp_V_reg_242 == 14'd0) ? 1'b1 : 1'b0);

assign icmp_ln897_1_fu_411_p2 = ((p_Result_152_fu_405_p2 != 22'd0) ? 1'b1 : 1'b0);

assign icmp_ln897_fu_379_p2 = (($signed(tmp_fu_369_p4) > $signed(31'd0)) ? 1'b1 : 1'b0);

assign icmp_ln908_fu_479_p2 = (($signed(lsb_index_fu_363_p2) > $signed(32'd0)) ? 1'b1 : 1'b0);

assign ireg_V_10_fu_898_p1 = v_assign_s_reg_1334;

assign ireg_V_fu_619_p1 = v_assign_reg_1329;


always @ (p_Result_159_fu_337_p3) begin
    if (p_Result_159_fu_337_p3[0] == 1'b1) begin
        l_fu_345_p3 = 32'd0;
    end else if (p_Result_159_fu_337_p3[1] == 1'b1) begin
        l_fu_345_p3 = 32'd1;
    end else if (p_Result_159_fu_337_p3[2] == 1'b1) begin
        l_fu_345_p3 = 32'd2;
    end else if (p_Result_159_fu_337_p3[3] == 1'b1) begin
        l_fu_345_p3 = 32'd3;
    end else if (p_Result_159_fu_337_p3[4] == 1'b1) begin
        l_fu_345_p3 = 32'd4;
    end else if (p_Result_159_fu_337_p3[5] == 1'b1) begin
        l_fu_345_p3 = 32'd5;
    end else if (p_Result_159_fu_337_p3[6] == 1'b1) begin
        l_fu_345_p3 = 32'd6;
    end else if (p_Result_159_fu_337_p3[7] == 1'b1) begin
        l_fu_345_p3 = 32'd7;
    end else if (p_Result_159_fu_337_p3[8] == 1'b1) begin
        l_fu_345_p3 = 32'd8;
    end else if (p_Result_159_fu_337_p3[9] == 1'b1) begin
        l_fu_345_p3 = 32'd9;
    end else if (p_Result_159_fu_337_p3[10] == 1'b1) begin
        l_fu_345_p3 = 32'd10;
    end else if (p_Result_159_fu_337_p3[11] == 1'b1) begin
        l_fu_345_p3 = 32'd11;
    end else if (p_Result_159_fu_337_p3[12] == 1'b1) begin
        l_fu_345_p3 = 32'd12;
    end else if (p_Result_159_fu_337_p3[13] == 1'b1) begin
        l_fu_345_p3 = 32'd13;
    end else if (p_Result_159_fu_337_p3[14] == 1'b1) begin
        l_fu_345_p3 = 32'd14;
    end else if (p_Result_159_fu_337_p3[15] == 1'b1) begin
        l_fu_345_p3 = 32'd15;
    end else if (p_Result_159_fu_337_p3[16] == 1'b1) begin
        l_fu_345_p3 = 32'd16;
    end else if (p_Result_159_fu_337_p3[17] == 1'b1) begin
        l_fu_345_p3 = 32'd17;
    end else if (p_Result_159_fu_337_p3[18] == 1'b1) begin
        l_fu_345_p3 = 32'd18;
    end else if (p_Result_159_fu_337_p3[19] == 1'b1) begin
        l_fu_345_p3 = 32'd19;
    end else if (p_Result_159_fu_337_p3[20] == 1'b1) begin
        l_fu_345_p3 = 32'd20;
    end else if (p_Result_159_fu_337_p3[21] == 1'b1) begin
        l_fu_345_p3 = 32'd21;
    end else if (p_Result_159_fu_337_p3[22] == 1'b1) begin
        l_fu_345_p3 = 32'd22;
    end else if (p_Result_159_fu_337_p3[23] == 1'b1) begin
        l_fu_345_p3 = 32'd23;
    end else if (p_Result_159_fu_337_p3[24] == 1'b1) begin
        l_fu_345_p3 = 32'd24;
    end else if (p_Result_159_fu_337_p3[25] == 1'b1) begin
        l_fu_345_p3 = 32'd25;
    end else if (p_Result_159_fu_337_p3[26] == 1'b1) begin
        l_fu_345_p3 = 32'd26;
    end else if (p_Result_159_fu_337_p3[27] == 1'b1) begin
        l_fu_345_p3 = 32'd27;
    end else if (p_Result_159_fu_337_p3[28] == 1'b1) begin
        l_fu_345_p3 = 32'd28;
    end else if (p_Result_159_fu_337_p3[29] == 1'b1) begin
        l_fu_345_p3 = 32'd29;
    end else if (p_Result_159_fu_337_p3[30] == 1'b1) begin
        l_fu_345_p3 = 32'd30;
    end else if (p_Result_159_fu_337_p3[31] == 1'b1) begin
        l_fu_345_p3 = 32'd31;
    end else begin
        l_fu_345_p3 = 32'd32;
    end
end

assign lsb_index_fu_363_p2 = ($signed(32'd4294967243) + $signed(sub_ln894_fu_353_p2));

assign lshr_ln897_fu_399_p2 = 22'd4194303 >> zext_ln897_fu_395_p1;

assign lshr_ln908_fu_491_p2 = zext_ln907_10_fu_475_p1 >> add_ln908_fu_485_p2;

assign m_47_fu_517_p3 = ((icmp_ln908_fu_479_p2[0:0] === 1'b1) ? zext_ln908_fu_497_p1 : shl_ln908_fu_511_p2);

assign m_48_fu_529_p2 = (zext_ln911_fu_525_p1 + m_47_fu_517_p3);

assign m_51_fu_545_p1 = m_s_fu_535_p4;

assign m_fu_471_p1 = $unsigned(sext_ln891_fu_323_p1);

assign m_s_fu_535_p4 = {{m_48_fu_529_p2[63:1]}};

assign man_V_46_fu_664_p2 = (54'd0 - p_Result_162_fu_660_p1);

assign man_V_47_fu_670_p3 = ((p_Result_161_fu_626_p3[0:0] === 1'b1) ? man_V_46_fu_664_p2 : p_Result_162_fu_660_p1);

assign man_V_49_fu_943_p2 = (54'd0 - p_Result_164_fu_939_p1);

assign man_V_50_fu_949_p3 = ((p_Result_163_fu_905_p3[0:0] === 1'b1) ? man_V_49_fu_943_p2 : p_Result_164_fu_939_p1);

assign mul_ln1192_fu_1264_p0 = sext_ln1118_28_reg_1345;

assign mul_ln1192_fu_1264_p1 = sext_ln1118_29_fu_1225_p1;

assign mul_ln1192_fu_1264_p2 = ($signed(mul_ln1192_fu_1264_p0) * $signed(mul_ln1192_fu_1264_p1));

assign mul_ln1193_fu_1238_p0 = sext_ln1118_28_reg_1345;

assign mul_ln1193_fu_1238_p1 = sext_ln1118_30_fu_1229_p1;

assign mul_ln1193_fu_1238_p2 = ($signed(mul_ln1193_fu_1238_p0) * $signed(mul_ln1193_fu_1238_p1));

assign mul_ln700_10_fu_1259_p0 = sext_ln1118_30_fu_1229_p1;

assign mul_ln700_10_fu_1259_p1 = sext_ln1118_reg_1339;

assign mul_ln700_10_fu_1259_p2 = ($signed(mul_ln700_10_fu_1259_p0) * $signed(mul_ln700_10_fu_1259_p1));

assign mul_ln700_fu_1233_p0 = sext_ln1118_reg_1339;

assign mul_ln700_fu_1233_p1 = sext_ln1118_29_fu_1225_p1;

assign mul_ln700_fu_1233_p2 = ($signed(mul_ln700_fu_1233_p0) * $signed(mul_ln700_fu_1233_p1));

assign or_ln581_10_fu_1109_p2 = (or_ln582_10_fu_1073_p2 | icmp_ln581_fu_969_p2);

assign or_ln581_fu_830_p2 = (or_ln582_fu_794_p2 | icmp_ln581_1_fu_690_p2);

assign or_ln582_10_fu_1073_p2 = (icmp_ln582_fu_1003_p2 | icmp_ln571_fu_957_p2);

assign or_ln582_fu_794_p2 = (icmp_ln582_1_fu_724_p2 | icmp_ln571_1_fu_678_p2);

assign or_ln603_46_fu_870_p2 = (and_ln585_fu_818_p2 | and_ln582_fu_788_p2);

assign or_ln603_47_fu_884_p2 = (or_ln603_fu_856_p2 | or_ln603_46_fu_870_p2);

assign or_ln603_48_fu_1135_p2 = (and_ln603_10_fu_1121_p2 | and_ln585_30_fu_1103_p2);

assign or_ln603_49_fu_1149_p2 = (and_ln585_29_fu_1097_p2 | and_ln582_10_fu_1067_p2);

assign or_ln603_50_fu_1163_p2 = (or_ln603_49_fu_1149_p2 | or_ln603_48_fu_1135_p2);

assign or_ln603_fu_856_p2 = (and_ln603_fu_842_p2 | and_ln585_28_fu_824_p2);

assign or_ln899_fu_457_p2 = (and_ln899_fu_451_p2 | a_fu_417_p2);

assign or_ln_fu_463_p3 = {{31'd0}, {or_ln899_fu_457_p2}};

assign p_Result_152_fu_405_p2 = (sext_ln891_fu_323_p1 & lshr_ln897_fu_399_p2);

assign p_Result_153_fu_443_p3 = sext_ln891_fu_323_p1[add_ln899_fu_437_p2];

assign p_Result_159_fu_337_p3 = {{10'd1023}, {p_Result_s_fu_327_p4}};

assign p_Result_160_fu_589_p5 = {{tmp_4_fu_581_p3}, {m_51_fu_545_p1[51:0]}};

assign p_Result_161_fu_626_p3 = ireg_V_fu_619_p1[32'd63];

assign p_Result_162_fu_660_p1 = tmp_5_fu_652_p3;

assign p_Result_163_fu_905_p3 = ireg_V_10_fu_898_p1[32'd63];

assign p_Result_164_fu_939_p1 = tmp_6_fu_931_p3;

integer ap_tvar_int_0;

always @ (sext_ln891_fu_323_p1) begin
    for (ap_tvar_int_0 = 22 - 1; ap_tvar_int_0 >= 0; ap_tvar_int_0 = ap_tvar_int_0 - 1) begin
        if (ap_tvar_int_0 > 21 - 0) begin
            p_Result_s_fu_327_p4[ap_tvar_int_0] = 1'b0;
        end else begin
            p_Result_s_fu_327_p4[ap_tvar_int_0] = sext_ln891_fu_323_p1[21 - ap_tvar_int_0];
        end
    end
end

assign ret_V_22_fu_1269_p2 = (mul_ln1192_fu_1264_p2 + mul_ln700_10_fu_1259_p2);

assign ret_V_fu_1243_p2 = (mul_ln700_fu_1233_p2 - mul_ln1193_fu_1238_p2);

assign s_V_fu_1169_p3 = ((or_ln603_50_fu_1163_p2[0:0] === 1'b1) ? select_ln603_69_fu_1155_p3 : 22'd0);

assign select_ln588_10_fu_1047_p3 = ((tmp_79_fu_1039_p3[0:0] === 1'b1) ? 22'd4194303 : 22'd0);

assign select_ln588_fu_768_p3 = ((tmp_77_fu_760_p3[0:0] === 1'b1) ? 22'd4194303 : 22'd0);

assign select_ln603_64_fu_862_p3 = ((and_ln585_fu_818_p2[0:0] === 1'b1) ? select_ln588_fu_768_p3 : trunc_ln583_fu_730_p1);

assign select_ln603_65_fu_876_p3 = ((or_ln603_fu_856_p2[0:0] === 1'b1) ? select_ln603_fu_848_p3 : select_ln603_64_fu_862_p3);

assign select_ln603_67_fu_1127_p3 = ((and_ln603_10_fu_1121_p2[0:0] === 1'b1) ? shl_ln604_fu_1055_p2 : trunc_ln586_10_fu_1035_p1);

assign select_ln603_68_fu_1141_p3 = ((and_ln585_29_fu_1097_p2[0:0] === 1'b1) ? select_ln588_10_fu_1047_p3 : trunc_ln583_10_fu_1009_p1);

assign select_ln603_69_fu_1155_p3 = ((or_ln603_48_fu_1135_p2[0:0] === 1'b1) ? select_ln603_67_fu_1127_p3 : select_ln603_68_fu_1141_p3);

assign select_ln603_fu_848_p3 = ((and_ln603_fu_842_p2[0:0] === 1'b1) ? shl_ln604_1_fu_776_p2 : trunc_ln586_fu_756_p1);

assign select_ln885_fu_605_p3 = ((icmp_ln885_fu_317_p2[0:0] === 1'b1) ? 64'd0 : bitcast_ln729_fu_601_p1);

assign select_ln915_fu_557_p3 = ((tmp_75_fu_549_p3[0:0] === 1'b1) ? 11'd1023 : 11'd1022);

assign sext_ln1118_28_fu_1181_p1 = $signed(s_V_fu_1169_p3);

assign sext_ln1118_29_fu_1225_p1 = $signed(X_R_V_q0);

assign sext_ln1118_30_fu_1229_p1 = $signed(X_I_V_q0);

assign sext_ln1118_fu_1177_p1 = $signed(c_V_fu_890_p3);

assign sext_ln55_fu_1207_p1 = $signed(i_lower_fu_1201_p2);

assign sext_ln57_fu_1213_p1 = i_0_reg_266;

assign sext_ln581_28_fu_720_p1 = sh_amt_fu_708_p3;

assign sext_ln581_29_fu_995_p1 = sh_amt_10_fu_987_p3;

assign sext_ln581_30_fu_999_p1 = sh_amt_10_fu_987_p3;

assign sext_ln581_fu_716_p1 = sh_amt_fu_708_p3;

assign sext_ln891_fu_323_p1 = tmp_V_reg_242;

assign sh_amt_10_fu_987_p3 = ((icmp_ln581_fu_969_p2[0:0] === 1'b1) ? add_ln581_fu_975_p2 : sub_ln581_fu_981_p2);

assign sh_amt_fu_708_p3 = ((icmp_ln581_1_fu_690_p2[0:0] === 1'b1) ? add_ln581_1_fu_696_p2 : sub_ln581_1_fu_702_p2);

assign shl_ln604_1_fu_776_p2 = trunc_ln583_fu_730_p1 << sext_ln581_28_fu_720_p1;

assign shl_ln604_fu_1055_p2 = trunc_ln583_10_fu_1009_p1 << sext_ln581_30_fu_999_p1;

assign shl_ln908_fu_511_p2 = m_fu_471_p1 << zext_ln908_1_fu_507_p1;

assign sub_ln581_1_fu_702_p2 = (12'd11 - F2_fu_684_p2);

assign sub_ln581_fu_981_p2 = (12'd11 - F2_10_fu_963_p2);

assign sub_ln894_fu_353_p2 = (32'd22 - l_fu_345_p3);

assign sub_ln897_fu_389_p2 = (5'd12 - trunc_ln897_fu_385_p1);

assign sub_ln908_fu_501_p2 = (32'd54 - sub_ln894_fu_353_p2);

assign sub_ln915_fu_569_p2 = (11'd11 - trunc_ln893_fu_565_p1);

assign temp_I_V_fu_1275_p4 = {{ret_V_22_fu_1269_p2[32:11]}};

assign temp_R_V_fu_1249_p4 = {{ret_V_fu_1243_p2[32:11]}};

assign tmp_4_fu_581_p3 = {{1'd0}, {add_ln915_fu_575_p2}};

assign tmp_5_fu_652_p3 = {{1'd1}, {trunc_ln565_fu_648_p1}};

assign tmp_6_fu_931_p3 = {{1'd1}, {trunc_ln565_10_fu_927_p1}};

assign tmp_74_fu_423_p3 = lsb_index_fu_363_p2[32'd31];

assign tmp_75_fu_549_p3 = m_48_fu_529_p2[32'd54];

assign tmp_77_fu_760_p3 = ireg_V_fu_619_p1[32'd63];

assign tmp_79_fu_1039_p3 = ireg_V_10_fu_898_p1[32'd63];

assign tmp_80_fu_1185_p4 = {{i_0_reg_266[31:10]}};

assign tmp_fu_369_p4 = {{lsb_index_fu_363_p2[31:1]}};

assign trunc_ln556_10_fu_901_p1 = ireg_V_10_fu_898_p1[62:0];

assign trunc_ln556_fu_622_p1 = ireg_V_fu_619_p1[62:0];

assign trunc_ln565_10_fu_927_p1 = ireg_V_10_fu_898_p1[51:0];

assign trunc_ln565_fu_648_p1 = ireg_V_fu_619_p1[51:0];

assign trunc_ln583_10_fu_1009_p1 = man_V_50_fu_949_p3[21:0];

assign trunc_ln583_fu_730_p1 = man_V_47_fu_670_p3[21:0];

assign trunc_ln586_10_fu_1035_p1 = ashr_ln586_fu_1029_p2[21:0];

assign trunc_ln586_fu_756_p1 = ashr_ln586_1_fu_750_p2[21:0];

assign trunc_ln893_fu_565_p1 = l_fu_345_p3[10:0];

assign trunc_ln894_fu_359_p1 = sub_ln894_fu_353_p2[21:0];

assign trunc_ln897_fu_385_p1 = sub_ln894_fu_353_p2[4:0];

assign xor_ln571_10_fu_1061_p2 = (icmp_ln571_fu_957_p2 ^ 1'd1);

assign xor_ln571_fu_782_p2 = (icmp_ln571_1_fu_678_p2 ^ 1'd1);

assign xor_ln581_10_fu_1115_p2 = (or_ln581_10_fu_1109_p2 ^ 1'd1);

assign xor_ln581_fu_836_p2 = (or_ln581_fu_830_p2 ^ 1'd1);

assign xor_ln582_10_fu_1079_p2 = (or_ln582_10_fu_1073_p2 ^ 1'd1);

assign xor_ln582_fu_800_p2 = (or_ln582_fu_794_p2 ^ 1'd1);

assign xor_ln585_10_fu_1091_p2 = (icmp_ln585_fu_1013_p2 ^ 1'd1);

assign xor_ln585_fu_812_p2 = (icmp_ln585_1_fu_734_p2 ^ 1'd1);

assign xor_ln899_fu_431_p2 = (tmp_74_fu_423_p3 ^ 1'd1);

assign zext_ln461_1_fu_644_p1 = exp_tmp_V_fu_634_p4;

assign zext_ln461_fu_923_p1 = exp_tmp_V_10_fu_913_p4;

assign zext_ln586_1_fu_746_p1 = $unsigned(sext_ln581_fu_716_p1);

assign zext_ln586_fu_1025_p1 = $unsigned(sext_ln581_29_fu_995_p1);

assign zext_ln891_fu_313_p1 = i_reg_253;

assign zext_ln897_fu_395_p1 = sub_ln897_fu_389_p2;

assign zext_ln907_10_fu_475_p1 = $unsigned(sext_ln891_fu_323_p1);

assign zext_ln908_1_fu_507_p1 = sub_ln908_fu_501_p2;

assign zext_ln908_fu_497_p1 = lshr_ln908_fu_491_p2;

assign zext_ln911_fu_525_p1 = or_ln_fu_463_p3;

always @ (posedge ap_clk) begin
    zext_ln891_reg_1313[31:1] <= 31'b0000000000000000000000000000000;
end

endmodule //fft_stage81
